### ISSUE TITLE
synchronizing leiningen resets the 'project' field in repl configuration

### ISSUE THREAD

**Issue by ohlo** [cursiveclojure/cursive#1002]
I have seen this in multi-module projects. my run configuration for a repl is for a sub-module, synchronizing resets it to the parent module.

hope that's clear.

cheers,
Henry

**Comment by cursiveclojure** [comment]
Hmm, that sounds very strange, I'll try to reproduce.

**Comment by ohlo** [comment]
Thanks. I've been playing with this more and actually I am less sure about synchronizing is the cause...it doesnt happen every time. it has flipped back a few times though to parent a few times though... I'll try to pin down exactly what it is and post back here.

**Comment by ohlo** [comment]
ok, I know what it is now! it relates to the version of the project changing. 

say you have a submodule on 0.1.1 and you create a run config 'run nRepl with leiningen' pointing to this project. now, if you go and change the lein project to 0.1.2 and run this config, it resets to the root proj, I suppose because there is no valid 0.1.1 project anymore.

**Comment by cursiveclojure** [comment]
Ohhh... that makes sense, great catch. I'll fix that.
