### ISSUE TITLE
Can't delete bracket/paren/quote unless it is selected/highlighted

### ISSUE THREAD

**Issue by trimtab613** [cursiveclojure/cursive#1003]
Frequently a bracket, parenthesis, or quote will not be removed from the text editor when I use backspace or delete on it. When this happens, deleting other characters is still possible, just these ones are broken. Other similar characters in the file are also "frozen". The only way to delete the character is to select it then use backspace or delete.

Not tested: non-Clojure code

Cursive 0.1.59
IntelliJ IDEA 14.1.4

**Comment by cursiveclojure** [comment]
This is because of Structural Editing, see [here](https://cursiveclojure.com/userguide/paredit.html).
