### ISSUE TITLE
Shortcut to wrap expression before/after caret in "comment" macro

### ISSUE THREAD

**Issue by madvas** [cursiveclojure/cursive#1007]
I think it would be helpful if one could set shortcut which wraps expression before or after caret in `(comment ...)` macro.

**Comment by danielcompton** [comment]
You could also achieve the same thing with the #_ reader macro.

**Comment by madvas** [comment]
Oh, didn't know that, thanks! Don't you know how would I set keyboard shortcut for that?

**Comment by danielcompton** [comment]
I'm not sure, I usually just type the two characters :) but now I want to go look for it.

**Comment by madvas** [comment]
I found out that this could be recorded as macro in Edit -> Macros . And then you can assign shortcut to that macro :)
