### ISSUE TITLE
Slurp slurps twice

### ISSUE THREAD

**Issue by neverfox** [cursiveclojure/cursive#1029]
```clojure
(baz|) (foo bar)
(foo bar)
```
`|` represents the cursor. If I slurp once, it behaves as if I slurped twice:

```clojure
(baz (foo bar)
     (foo bar))
```

It should only be (as seen in Emacs):
```clojure
(baz (foo bar))
(foo bar)
```
In fact, if I hit undo, it backs up to the proper form, almost as if it had put two operations on the undo stack.

**Comment by danielcompton** [comment]
I can't reproduce this, what are your keybindings for Slurp Forwards?

**Comment by neverfox** [comment]
I cannot either now. There must have been a stray paren somewhere in the file I was working in. Thanks for checking thought.
