### ISSUE TITLE
splice sexp keybinding not worked

### ISSUE THREAD

**Issue by zjhmale** [cursiveclojure/cursive#1033]
I just install idea and cursive in a new laptop and import the old settings from idea to idea.
And everything seems works fine but when i want to splice a s-expression it seems not override the default mac os key binding.
When i type `⌥S` it just show `ß` but not splice the s-expression where the cursor in, how can i fix it? other keybindings in cursive all works fine for me.

**Comment by zjhmale** [comment]
and i use osx 10.10.4 and idea 14.1.14 and cursive 0.1.60

**Comment by cursiveclojure** [comment]
Thanks for the details. Which JDK do you use to run IntelliJ? You can see that under *IntelliJ IDEA->About IntelliJ IDEA*.

**Comment by zjhmale** [comment]
i use jdk7

<img width="342" alt="2015-08-23 3 43 50" src="https://cloud.githubusercontent.com/assets/6234553/9427390/cca19f5a-49ad-11e5-9889-ebd85f46e0ec.png">

**Comment by zjhmale** [comment]
the is a short cut from the IntelliJ IDEA->About IntelliJ IDEA.

**Comment by zjhmale** [comment]
if can not fix this issue i can not work with clojure happily...

**Comment by cursiveclojure** [comment]
So I think this is a JDK bug, see #962. I believe that running IntelliJ under Apple's JDK6 fixes the problem, and it will also be fixed in 1.8u60, but I don't know when JetBrains will switch their bundled JDK to that version.

**Comment by zjhmale** [comment]
ok i will try 1.8u60

**Comment by cursiveclojure** [comment]
I believe it hasn't been released yet. At the moment on the mac, the best option is to use Apple's 1.6 JDK unless you have a good reason not to.

**Comment by zjhmale** [comment]
uh.. i just startup with the new laptop with the oracle jdk7 straight without install the official jdkformac maybe cause the issue is [this](https://support.apple.com/kb/DL1572?locale=zh_CN) the right Apple's 1.6 JDK ?

**Comment by zjhmale** [comment]
thx!!! after i install the Apple's 1.6 JDK it fixed :)

**Comment by cursiveclojure** [comment]
Great!
