### ISSUE TITLE
Intellij freezes completely when running a clojure application with 0.1.61

### ISSUE THREAD

**Issue by pkozikow** [cursiveclojure/cursive#1041]
I couldn't find anything revealing in the logs. I had to force quit and revert to 0.1.60.

**Comment by favila** [comment]
Ran in to this too: it sets one core 100%. One time it did recover (after about a minute), but a subsequent time it did not. I couldn't figure out the responsible thread using VisualVM.

I was able to trigger it by reloading a namespace. I have a hunch it's related to regexes or parsing somehow.

I'm using Intellij IDEA CE 14.1.4 on Ubuntu 15.04 with openjdk-8-amd64

**Comment by cursiveclojure** [comment]
A couple of people have reported this. I think Francis might be right, I changed one of the folding regexes and I suspect that it's prone to exponential backtracking. If you can reproduce it, does it go away if you unselect *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;Prettify stacktrace elements using folding* and *Fold stacktrace lines from outside project*?

**Comment by cursiveclojure** [comment]
Even better, there's a build [here](http://colinfleming.net/regexp/cursive-14.1-0.1.61.zip) (for v14.1) with that change reverted. If someone could confirm that it fixes the problem for them, that would be great.

**Comment by favila** [comment]
Turning those options off didn't change anything.
 
To reproduce, I start a REPL and then exec "Load file in REPL" command from a clojure namespace.  Empty namespaces eventually load, so I think the length of the freeze is proportional to the size of the  namespace or its required namespaces.

Also found the name of the runaway thread: "AWT-EventQueue-0.14.1.4#IC-141.1532.4,eap:false" if that means anything to you. (Maybe explains why it locks the UI.)

I will try your build in a sec

**Comment by favila** [comment]
Your build fixes it.

**Comment by cursiveclojure** [comment]
Fantastic, thanks @favila! I'll do a build now.

**Comment by cursiveclojure** [comment]
This fix is out now in 0.1.62.
