### ISSUE TITLE
"unknown response keys :state" in REPL

### ISSUE THREAD

**Issue by martinraison** [cursiveclojure/cursive#1050]
I am getting lots of DEBUG messages in my Cursive remote REPLs:

    DEBUG: unknown response keys :state

Any clue as to what could be causing this? I don't remember changing the remote REPL's leiningen or nrepl version recently. Tested with cursive v0.1.60, same issue. Also, as a workaround, is it possible to disable the DEBUG output?

**Comment by martinraison** [comment]
Upgrading to leiningen 2.5.2 fixed the issue.

**Comment by cursiveclojure** [comment]
Another user reported this the other day - it turned out to be something in his lein profiles left over from Cider. I'll check with the Cider guys if they're adding that key as part of their nREPL integration.

**Comment by romstad** [comment]
Since this morning, I also have this problem, and upgrading leiningen to 2.5.2 does not help. The hypothesis that it has something to do with Cider is interesting, as I did briefly try out the most recent version of Cider last night. However, commenting out everything Cider related in my profiles.clj does not fix the issue. I even tried deleting profiles.clj altogether, but the message still appears.

Is it possible that Cider somehow messes with some relevant file other than ~/.lein/profiles.clj? If yes, which one could it be?

**Comment by cursiveclojure** [comment]
One thing to note is that annoyingly, Leiningen caches the profile information internally so you have to restart IntelliJ after modifying your profile. Does that help? I'm working on a fix for that (among many other things) right now, actually.

**Comment by romstad** [comment]
Thanks, restarting IntelliJ after changing my profiles.clj did the trick!

For the record, the plugin [cider/cider-nrepl "0.10.0-SNAPSHOT"] turned out to be the offending line.

**Comment by dpp** [comment]
FWIW -- I'm running Cider and Cursive... sometimes Emacs is better for CLJ dev and sometimes Cursive is. It's be super excellent if the cider nrepl 0.10.0 could co-exist with Cursive.

**Comment by cursiveclojure** [comment]
@dpp Fair enough, I'll just ignore that message in the next build.

**Comment by dpp** [comment]
Tnx @cursiveclojure Also, I *really* want to give you money for Cursive. When will I be able to do that?

**Comment by cursiveclojure** [comment]
@dpp Very soon! I was working on that when the JetBrains subscription kerfuffle put it on hold, and I got wrapped up in an enormous refactoring. I'll be writing a post soon with my planned licensing scheme, and I hope to have it on sale within a month or so.

**Comment by dpp** [comment]
**Yay!!**
