### ISSUE TITLE
Feature Request: Configure macros to know when they bind symbols

### ISSUE THREAD

**Issue by tel** [cursiveclojure/cursive#1058]
Today if I write a macro

```clojure
(defmacro my-let [bindings & body] `(let [~@bindings] ~@body))
```

Cursive will not detect that `my-let` establishes new bound symbols and state that their values cannot be resolved.

```clojure
(my-let [x 1 ; x is highlighted
         y 2] ; y is highlighted
  (+ x y)) ; x and y are highlighted here too
```

There's no obvious way to know when these kinds of bindings are in play and to account for them, but this feature would be a strong nice-to-have in a lisp-like language.

**Comment by danielcompton** [comment]
This feature is being tracked in #147.

**Comment by tel** [comment]
Yup! Closing
