### ISSUE TITLE
suport for android libraries

### ISSUE THREAD

**Issue by roti** [cursiveclojure/cursive#1071]
lein-droid offers support for android libraries by allowing to specify ```:extension "aar"``` in the dependency list. For example:
```clojure
  :dependencies [[org.clojure-android/clojure "1.7.0-r2"]
                 [neko/neko "4.0.0-alpha5"]
                 [com.google.android.gms/play-services-maps "7.8.0" :extension "aar"]
                 [com.google.android.gms/play-services-location "7.8.0" :extension "aar"]]
```

cursive does not seem to see these libraries, the classes don't show up in the code completion popup.

**Comment by danielcompton** [comment]
Looks like this is a dupe of your other issue #1061?

**Comment by roti** [comment]
Oops, completely forgot about it.
