### ISSUE TITLE
Breaks Java editor: "Invert 'if' condition" breaks code when 'if' block contains a multi line statement

### ISSUE THREAD

**Issue by orfjackal** [cursiveclojure/cursive#1087]
It seems that when Cursive 0.1.62 plugin is enabled, it causes a bug in Java intention actions. See the issue and its comments at https://youtrack.jetbrains.com/issue/IDEA-145556

**Comment by cursiveclojure** [comment]
This is fixed for the next build. I'll get this out ASAP.

**Comment by cursiveclojure** [comment]
This has been released in 0.1.63, out now.
