### ISSUE TITLE
Unused library popup contains unrendered markup [0.1.63]

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#1094]
![fullscreen_10_7_15__11_00_am](https://cloud.githubusercontent.com/assets/52660/10346211/c93572ee-6ce2-11e5-9120-3f9550ea553f.png)

```
Library <a href="http://library/Leiningen:org.clojure/core.async....">Leiningen:org.clojure/core.async..</a> is not used
```

**Comment by cursiveclojure** [comment]
I'm going to close this since it's actually an IntelliJ bug, it also happens for Maven libraries. I don't supply the contents of that tooltip.
