### ISSUE TITLE
Windows 8.1/10: REPL wouldn't start

### ISSUE THREAD

**Issue by mobius-eng** [cursiveclojure/cursive#1100]
The attempt to start REPL results in the following error message:

```
3:34:15 PM CompilerException: java.lang.IllegalArgumentException: No implementation of method: :urls of protocol: #'mranderson045.javaclasspath.v0v2v2.clojure.java.classpath/URLClasspath found for class: com.intellij.ide.plugins.cl.PluginClassLoader, compiling:(track_state.clj:56:8)
```

Project file:
```clojure
(defproject example "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [net.mikera/core.matrix "0.41.0"]]
  :jvm-opts ^:replace ["-server"])
```

JDK 1.8 (latest, at least it was 2 weeks ago, from Oracle site)

The REPL for this project starts under Emacs/CIDER without any problem.

**Comment by camwest** [comment]
+1

**Comment by dgomesbr** [comment]
Windows 7 Professional and Idea 14.1.5

![screenshot](http://i.imgur.com/q6IVH1Q.jpg)

> 14:14:15 Error reading C:\Dev\workspace_idea\metabase\project.clj
         java.lang.IllegalArgumentException: No implementation of method: :urls of protocol: #'mranderson045.javaclasspath.v0v2v2.clojure.java.classpath/URLClasspath found for class: com.intellij.util.lang.UrlClassLoader, compiling:(track_state.clj:57:8)
         No implementation of method: :urls of protocol: #'mranderson045.javaclasspath.v0v2v2.clojure.java.classpath/URLClasspath found for class: com.intellij.util.lang.UrlClassLoader

**Comment by dgomesbr** [comment]
Same steps on MINT Linux works as expected.

**Comment by cursiveclojure** [comment]
Closing this, it's tracked in #1114. It's a downstream bug, it can be worked around by removing `cider-nrepl` from profiles when running under Cursive.

**Comment by dgomesbr** [comment]
@cursiveclojure how could I do it? Trying to learn clojure while having that kinda of problem is challenging.

**Comment by cursiveclojure** [comment]
@dgomesbr My apologies, I thought I'd replied to this. This bug is fixed in a later version of Cursive, upgrading should fix it.
