### ISSUE TITLE
Doesn't recognise short form anonymous functions #(...)

### ISSUE THREAD

**Issue by mrkyle7** [cursiveclojure/cursive#1101]
When typing in an anonymous function with the #() syntax, it doesn't recognise this as a normal bracket, ie won't automatically create the closing bracket. This can be annoying when adding it to a map function, as something like #(not (nil? %)) is tricky to get the matching brackets working properly.

**Comment by cursiveclojure** [comment]
I can't reproduce this, it works fine for me. So if I type `#` and then `(` I end up with `#(|)` where `|` represents the caret. Is that not what you see?

**Comment by mrkyle7** [comment]
Thanks for the quick response. I can confirm that typing # then ( works as you described. 

To reproduce, type (map) then before ")" type #( - mine ends up like: "(map #()"  and not "(map #())"

Without the #, it works ok- ie (map ())

**Comment by danielcompton** [comment]
I can't reproduce this either. Can you check you've got structural editing turned on and you don't have any keyboard shortcuts overriding `(`? Unlikely I know, but worth checking.

**Comment by mrkyle7** [comment]
Ah, turning structural editing on fixes it. Haven't gotten used to that yet, so normally turn it off. I'll brave it and keep it turned on in future :)
Thanks
