### ISSUE TITLE
Synchronize lein project missing from launch steps

### ISSUE THREAD

**Issue by bbss** [cursiveclojure/cursive#1109]
I was recently bitten by a bug that made it seem the project.clj was only read once. Running through the command line worked as expected. Updates to the :dependencies did not get installed when running the task and I noticed that others still have the option of "synchronize leinigen projects" in my _before launch_ options.

The action is available from the actions menu and that seemed to solve it.

I also needed to manually remove a dependency on an old react (12 where we are at 14 now) that none of the projects dependencies depended on when inspecting lein deps :tree. Before removing that the wrong version of react got installed when running through cursive. But not when running through the command line.

I am on osx and was on 143.116 (latest at the time) but after updating to the next version 143.249.6 the option is still not available.

Any additional details needed?

**Comment by shaharz** [comment]
+1. Synchronize leiningen projects was missing from the automatically created configuration (imported Leiningen project) as well as newly created ones. Took a while to figure out why deps weren't getting pulled...

Running 0.1.70 on IntelliJ IDEA 15.
