### ISSUE TITLE
Option to keep namespace stable after loading code

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#111]
When loading new code into the REPL, Cursive must change the namespace for the code change to take proper effect.

However, more often than not, I end up having to switch back to the old namespace (usually "user").

I would like the option, perhaps in the Clojure facet, to keep the namespace stable (revert back to the active namespace after loading code).

**Comment by cursiveclojure** [comment]
This is (finally!) fixed for the next drop. There's a new option in the IDE settings, "Load forms in REPL namespace". When selected, forms evaluated using 'Run form before cursor in REPL' and 'Run top form in REPL' will be executed in the REPL namespace. If not, they will be executed in the file's namespace. Note that this is *not* selected by default, which is a change in the default behaviour. This is to minimise confusion for people coming from other tools, which pretty universally work like this.

**Comment by cursiveclojure** [comment]
There's also one special case I forgot to mention - if you execute a form from a file that has no namespace, it will always be executed in the REPL namespace, regardless of what the setting is set to.
