### ISSUE TITLE
still having problems with lein modules with 0.1.64 

### ISSUE THREAD

**Issue by ohlo** [cursiveclojure/cursive#1112]
Hopefully this is pebkac, but my modules projects still not working. 

when trying to run a local repl for the below example, (run nrepl with lein, choosing the sub-module), I get :

09:41:56 Error reading /dev/test-modules/sub_module/project.clj: Could not locate lein_modules/plugin__init.class or lein_modules/plugin.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
09:41:58 Leiningen aborted: exit code 1: (show balloon)
09:42:04 Error running sub: Could not calculate REPL command

I tried adding the plugin to the dependencies as a hacky workaround, but that didnt help.

here is a simple set up to recreate:

in parent dir project.clj:
```
(defproject test-modules "0.1.0-SNAPSHOT"
  :plugins [[lein-modules "0.3.11"]]
  :modules {
            :versions { org.clojure/clojure "1.7.0" }
            })
```
in sub-module dir project.clj:
```
(defproject test-modules/sub-module "0.1.0-SNAPSHOT"
  :plugins [[lein-modules "0.3.11"]]
  :dependencies [[org.clojure/clojure _]
                 [lein-modules "0.3.11"]])
```

**Comment by cursiveclojure** [comment]
I have a fix for this, I'll do a build shortly.

**Comment by cursiveclojure** [comment]
This is fixed in 0.1.65, just released.

**Comment by ohlo** [comment]
cheers. 

i hadn't seen your email about beta testing until today or i would have tried earlier.

**Comment by da-z** [comment]
Having a similar problem, but with a newer build (0.1.72-15). Is this a regression?

Could not locate lein_environ/plugin__init.class or lein_environ/plugin.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.

```clj
:plugins [[lein-environ "1.0.1"]]
```

Thank you!
