### ISSUE TITLE
Project not picking up SNAPSHOT deps

### ISSUE THREAD

**Issue by shmish111** [cursiveclojure/cursive#1113]
I have a lein project which works fine so far however when I check out a particular branch that has some dependencies with version `0.0.0-SNAPSHOT` the editor cannot find the namespaces. The dep shows up in the tree in the lein window however in the editor I get a yellow highlight as it can't find the namespace and if I control-click on the namespace alias it does not open the dependency namespace as it does with non-SNAPSHOT deps.

**Comment by shmish111** [comment]
The repl seems to load the namespace ok although I also can't control-click through to my dep namespace

**Comment by cursiveclojure** [comment]
Does the dep get a library created for it? You can see this in the project structure window (_File->Project Structure..._). Check that the dep has a library created for it in the Libraries view, and also check that your module has that library listed in its dependencies in the Modules view.

**Comment by shmish111** [comment]
The dep is in Libraries if it's not the SNAPSHOT but it is not there if it is a SNAPSHOT. It is in the dependencies in the module view even though it is not in the project structure library.

**Comment by shmish111** [comment]
Also, if I add the dep as a module in my project then it is picked up correctly, my parent namespace can see the dep namespace properly. However in the dep I also have snapshot deps and they are not picked up, so it's not just 1 particular project.

**Comment by cursiveclojure** [comment]
Ok, I'll see if I can reproduce this. Is it for any snapshot deps, or only ones with version `0.0.0-SNAPSHOT`?

**Comment by shmish111** [comment]
Ah interesting, it seems to work if I change to `0.0.1-SNAPSHOT` so I guess something somewhere can't cope with it being 0. Should be easier to track down I guess.

**Comment by cursiveclojure** [comment]
I have a dev build which I think should fix this problem, could you drop me a mail at cursive@cursiveclojure.com if you're interested in trying it?

**Comment by cursiveclojure** [comment]
Actually, I went ahead and released this. Please feel free to re-open if 0.1.66 doesn't fix your problem.

**Comment by cursiveclojure** [comment]
Reopening since this is not fixed for at least one user. Are your snapshot deps coming from a custom repo?
