### ISSUE TITLE
Leiningen not picking up explicit version of a snapshot dependency

### ISSUE THREAD

**Issue by stijnopheide** [cursiveclojure/cursive#1118]
When specifying an explicit version of a SNAPSHOT dependency, it is not being picked up.

e.g.

```[yada "1.0.0-20150903.093751-9"]```

it gets properly picked up when specifying

```[yada "1.0.0-SNAPSHOT"]```

That however always uses the latest snapshot version.

**Comment by cursiveclojure** [comment]
This is fixed for the next build.
