### ISSUE TITLE
unknown status state and unknown response keys :changed-namespaces, :repl-type

### ISSUE THREAD

**Issue by edipofederle** [cursiveclojure/cursive#1124]
Hi, when I start a REPL in some project, many DEBUG messages are shown while I type:

![screen shot 2015-10-29 at 10 57 59 am](https://cloud.githubusercontent.com/assets/50778/10819255/3a0b5874-7e2e-11e5-949a-ea0816646cb1.png)

IntelliJ 14.1.5 (Community Edition)

Thanks in advance.

**Comment by cursiveclojure** [comment]
Yes, this appears to be due to CIDER, and is being tracked in #1120.
