### ISSUE TITLE
Upgrading to 0.1.67 disabled clojurescript repl

### ISSUE THREAD

**Issue by OliverM** [cursiveclojure/cursive#1127]
I upgraded to 0.1.67 (not realising it was a major change) and the transition process failed with a warning of an illegal character in the path to my project.clj file. I saw on your site that you can replaced the new project settings with the archived version, which I did, but the cljs repl is still not working.

The cljs repl was set up with a script folder containing a repl.clj file, as set out here:
https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL

After upgrading to 0.1.67, and running the cljs repl, a clojure repl launches but doesn't initiate the cljs figwheel connection, just acts identically to the standard clojure repl.

Is there an automated way to resolve this, or a manual series of steps I can follow to get my cljs repl back? Thanks!

**Comment by cursiveclojure** [comment]
Can you attach a screenshot of what your REPL run config looks like?

**Comment by OliverM** [comment]
Sure...

![screen shot 2015-10-29 at 9 09 12 p m](https://cloud.githubusercontent.com/assets/710458/10832144/6e7e2a16-7e81-11e5-9407-82f9ce1acac6.png)

**Comment by cursiveclojure** [comment]
It looks like your run config has been switched to a Leiningen one - instead of "Run nREPL with Leiningen" select "Use clojure.main in normal JVM process".

**Comment by OliverM** [comment]
That did the trick, thanks! Is it okay for me to keep running the 0.1.67 version in this state, or should I revert to an earlier version? I didn't see how to do that from the IntelliJ interface (that might be my failure to decipher it's various controls).

**Comment by cursiveclojure** [comment]
No, as long as it's working you can absolutely keep using it. When upgrading to `0.1.64+`, there's a migration that happens to the run configs. Occasionally people have had problems with that, I'm not sure why. Once it's fixed up by hand it should work fine.

I'll close this issue, feel free to reopen if you have more issues with this.
