### ISSUE TITLE
Type hint and symbols resolve failed for clojurescript

### ISSUE THREAD

**Issue by shisoft** [cursiveclojure/cursive#1145]
I have upgraded the IntelliJ to 15 and get the newest version (0.1.69) of cursive. It seems like all symbols are highlighted including core functions in cljs, indicates the symbols cannot been resolved.

**Comment by cursiveclojure** [comment]
@shisoft Sometimes when upgrading the indexes can get corrupted. Try File->Invalidate Caches and restart... and see if that helps.

**Comment by shisoft** [comment]
I have tried invalidate and restart twice, it does not work for me. I also cannot get any exception info fr reference
![screenshot from 2015-11-08 09 32 41](https://cloud.githubusercontent.com/assets/3405885/11018247/bf181f00-85fb-11e5-9303-4c81706e9844.png)

**Comment by cursiveclojure** [comment]
Can you check that your leiningen project is added to the leiningen toolwindow correctly? Check it in _View->Tool Windows->Leiningen_, if it's not added there then right-click it in the project view and select "Add as Leiningen project". Alternatively, if you open your `project.clj` Cursive will warn you if the project is not correctly registered and give you a link to register it.

If none of that works, let me know and we can try more options.

**Comment by shisoft** [comment]
I tried 'Add As Leininigen Project' and fixed this problem. Thanks for the support.

**Comment by cursiveclojure** [comment]
Great, thanks for letting me know!
