### ISSUE TITLE
REPL printing of namespaced symbols as values in a collection is broken

### ISSUE THREAD

**Issue by levand** [cursiveclojure/cursive#1146]
Some examples:

```
(edn/read-string "{foo/bar baz/boz}")
=> {foo /, bar baz, / boz}

(edn/read-string "#{foo/bar}")
=> #{foo / bar}

(edn/read-string "[foo/bar]")
=> [foo / bar]

(edn/read-string "(foo/bar)")
=> (foo / bar)
```

This is happening in 0.1.69, in IntelliJ 15 community edition, with the default REPL settings.

Thanks!

**Comment by cursiveclojure** [comment]
Ouch, that's bad - that must be the parsing for the new formatting. I'll fix that now.

**Comment by levand** [comment]
Thanks!

Love the new formatting, by the way.

**Comment by cursiveclojure** [comment]
Thanks! Most of the credit goes to @brandonbloom for fipp, which is excellent.

This is fixed in the next build, I'll push it out shortly.
