### ISSUE TITLE
[bug] Repl crash with infinite commas

### ISSUE THREAD

**Issue by kwladyka** [cursiveclojure/cursive#1157]
Just run that and intellij will crash:
```{(keyword "ab cd") 1}```

The problem is because of space in string. In ```lein repl``` it works.

**Comment by biggert** [comment]
I've been having this issue lately as well. Turning off the new pretty printing feature in the REPL will fix it.

**Comment by vvvvalvalval** [comment]
+1 having the issue too. Too bad, I really love this pretty printing feature.

**Comment by neverfox** [comment]
+1

**Comment by cursiveclojure** [comment]
This is fixed for the next build. Note that this will cause the pretty printing to be incorrect, since `{:ab bc 1}` will be parsed as a map of `:ab` to `bc`, and the `1` as an unbalanced key. There's no way I can think of to handle this better than that.

**Comment by cursiveclojure** [comment]
Actually, I've changed the way this works. Output containing invalid/unreadable forms (which these are) will be printed verbatim, so you won't get any pretty printing of them. See #1169 for discussion.

**Comment by neverfox** [comment]
^^ :+1:
