### ISSUE TITLE
Unhappy smile keyword is throwing REPL into the death loop

### ISSUE THREAD

**Issue by juskrey** [cursiveclojure/cursive#1166]
IDEA  14.1.5
cursive 0.1.70

This works:
```clojure
(keyword ")")
=> :)
```

This dies:
```
(keyword "(")
```

While this is a reduced example, it was actually derived from the pretty common use case, when various database calls return results like
```clojure
{:scope_identity() 9}
```

**Comment by cursiveclojure** [comment]
This is fixed as part of the fix for #1157. As with that case, the formatting will be wrong since `:scope_identity()` will be parsed as two elements `:scope_identity ()` so the map elements will be misaligned, but it won't crash IntelliJ.

**Comment by cursiveclojure** [comment]
Actually, I've changed the way this works. Output containing invalid/unreadable forms (which these are) will be printed verbatim, so you won't get any pretty printing of them. See #1169 for discussion.

**Comment by juskrey** [comment]
Thanks, sounds reasonable!
