### ISSUE TITLE
Figwheel repl hangs before giving a prompt

### ISSUE THREAD

**Issue by imrekoszo** [cursiveclojure/cursive#1173]
I am following the guide at https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL 

The only difference in tools used is the cursive version: the guide specifies ```0.1.62``` and I have ```0.1.70``` installed.

The repl comes up but the last line it prints is ```Prompt will show when figwheel connects to your application``` and then it hangs without giving a prompt. No commands work after this happens.

The issue persists even when I downgrade to ```0.1.69```. I couldn't try ```0.1.62``` as it has already expired.

IntelliJ IDEA 15.0.1
Build #IC-143.382, built on November 10, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

**Comment by imrekoszo** [comment]
Looks like the prompt does appear when I load the website in a browser. Closing issue.

**Comment by cursiveclojure** [comment]
Yes, this is a little confusing but it works the same way with `lein repl`.
