### ISSUE TITLE
Option to align arguments to certain forms

### ISSUE THREAD

**Issue by mfikes** [cursiveclojure/cursive#1174]
The _Editor > Code Style > Clojure > Default to Only Indent_ preference is nice, but for some reason, feels odd when applied to certain forms. 

The ones that jump out to me immediately are the logical connectives.

I recently discovered that @swannodette must evidently feel the same, as he _manually_ reformatted [to achieve this](https://github.com/clojure/clojurescript/commit/d63c22373ddaa97d62704038190d852ac2ed6ed7).

Why? I *think* this occurs for me when the arguments to a given form are "equivalent" or "interchangeable" or "of the same type" in some sense. And maybe it is exaggerated for the logical connectives because you want to visually scan code vertically and easily see which term might be important.

In terms of concrete examples to consider:

Today you can

```clojure
(when (or alpha
        beta)
  (println "hello"
    (get-user-name)))
```

or 

```clojure
(when (or alpha
          beta)
  (println "hello"
           (get-user-name)))
```

But it would be nice to

```clojure
(when (or alpha
          beta)
  (println "hello"
    (get-user-name)))
```

**Comment by mfikes** [comment]
@thheller showed me that it is already possible to do this (via Alt-Enter).

**Comment by cursiveclojure** [comment]
Right, as the name implies, *Default to indent only* is just a default, you can override it for any form.
