### ISSUE TITLE
Attempting to print the type of a primitive array puts the REPL into an infinite loop

### ISSUE THREAD

**Issue by ghoustonjr** [cursiveclojure/cursive#1176]
Attempting to print the type of a primitive array puts the REPL into an infinite loop. This can be demonstrated with the following expression:

`(type (byte-array 10))`

That should print `[B`. With Cursive 0.1.70 and IntelliJ 15.0.1 it triggers an infinite loop during which the REPL will repeatedly print empty new lines until it's terminated.

This only happens if "Pretty print REPL return Values" is checked in the "Languages & Frameworks > Clojure" settings menu. This happens from any lein repl used from Cursive, whether it's local or remote. This doesn't happen in the clojure.main REPL, and it doesn't happen in a lein REPL outside of Cursive.

Thanks for Cursive! It's a fantastic tool.

**Comment by cursiveclojure** [comment]
This is fixed in the next build. See #1169 for a description of the fix and some discussion.

**Comment by rsachdeva** [comment]
👍
