### ISSUE TITLE
"Convert outer #() to fn" should replace % arguments with named args

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#1185]
I used the "Convert outer #() to fn" inspection which was really neat. I noticed that it removes `%` but doesn't replace it with named args. It could be good to put the user into the function args declaration and get them to type the names of the args that were previously anonymous.

**Comment by cursiveclojure** [comment]
It should do this, actually, if it doesn't it's a bug. Do you have a reproduction case?

**Comment by danielcompton** [comment]
Oops, looking back through my history, I hadn't used the `%` in the outer function yet which is why it wasn't replaced. My mistake, I verified it worked after retrying now.
