### ISSUE TITLE
Piggieback middleware does not work from repl 

### ISSUE THREAD

**Issue by Mamun** [cursiveclojure/cursive#123]
Hi 

When I start paggiback repl from repl, it start and connect to browser repl. But when send command like (js/alert "Hello"), it said- No such namespace: js. 

But the project is working fine with command line mode. 

Project file repl option:
:repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}

Start piggieback:
(p/cljs-repl  :repl-env (doto
                                 (cljs.repl.browser/repl-env :port 9000)
                                 (cljs.repl/-setup))
      

BR,
Mamun

**Comment by cursiveclojure** [comment]
Is this still a problem? I know many people are using piggiexack-based REPLs, so I'm assuming this works. Please re-open if not.
