### ISSUE TITLE
Debug for leiningen run configuration does nothing

### ISSUE THREAD

**Issue by also** [cursiveclojure/cursive#153]
I have a simple leiningen run configuration. It runs without any issues. However, debugging the same configuration does nothing: there aren't any visible error messages, and the debugger doesn't start.

I'm using IDEA 13.0 and 0.1.09.

**Comment by cursiveclojure** [comment]
I made some steps towards this, unfortunately it's tricky because lein shells a subprocess for whatever it's running. I need to figure out whether I can make IntelliJ start one process but then debug another different one.
