### ISSUE TITLE
No Quick Doc for some special forms like "if" or "do"

### ISSUE THREAD

**Issue by aadrian** [cursiveclojure/cursive#210]
The "if" special form (or "do" or "new") doesn't seem to show in the QuickDoc (Ctrl+Q) any documentation, e.g. the one can read with ```(doc if)```

**Comment by hansgru** [comment]
Any news o this issue? Especially for new users would be very useful if the documentation that ```(doc something)``` provides anyway would be displayed, e.g. for ```quote```, ```var``` too
