### ISSUE TITLE
Changes to leiningen plugin versions not applied on leiningen sync

### ISSUE THREAD

**Issue by bellkev** [cursiveclojure/cursive#220]
I had v0.1.1 of the cemerick/austin plugin in my project.clj, and it loaded okay when I started a repl. However, after updating the plugin version to v0.1.4-SNAPSHOT, I discovered (after trying a lot of other things first :P), that the repo session was still referring to v0.1.1 of the jar in my local maven repo (running lein repo in the command line worked okay).

I ended up blowing away my .m2 directory re-syncing, still had some errors, did some more troubleshooting and restarting, and finally it worked okay. I'm afraid to fiddle with it anymore now that it's working, but please let me know if you need help reproducing it.

(My Cursive version when I had this issue was 0.1.10)

**Comment by danielcompton** [comment]
Reading this, it seems like your 'repo session' and `lein repo` are typos for REPL? If so then this is as expected, Cursive (and most other REPL environments) won't update dependencies in a running REPL if you change them in the project.clj and refresh them. 

It is possible to update your classpath with new JARs through https://github.com/pallet/alembic, though I'm not sure how it would interact with Cursive.

I think this can be closed?

**Comment by cursiveclojure** [comment]
I agree, unless I'm misunderstanding the issue. Please let me know if that's not the case.
