### ISSUE TITLE
Indentation wrong for multi line docstrings

### ISSUE THREAD

**Issue by cjkent** [cursiveclojure/cursive#252]
Pressing enter with the caret in the docstring indents the new line too far instead of aligning it with the previous line. And each time a new line is added the lines above are indented too, excluding the first.

e.g.
```clojure
(defn foo
  "abc[caret]"
  )
```

Press enter and the docstring becomes

```
  "abc
     "
```

Type some more and press enter

```
  "abc
        abc
        "
```

Type some more and press enter again

```
  "abc
           abc
           abc
           "
```

**Comment by cursiveclojure** [comment]
I haven't explicitly fixed this, but I've made a lot of formatting fixes recently and this seems to work correctly. If you're still seeing this, please re-open.
