### ISSUE TITLE
REPL - quick way to change to recent namespace

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#255]
I tend to fly back and forth between namespaces as I'm doing the REPL-oriented test and debug thing.

If there was a key, say **^M** that would raise a list of a few recent namespaces, to switch between them, that would save me a lot of trouble.

I say ^M since it has a similar function in the commit dialog; showing recent commit messages.

**Comment by cursiveclojure** [comment]
Assuming this is fixed, please re-open if not.
