### ISSUE TITLE
syn the lein project is extreme slow

### ISSUE THREAD

**Issue by weejulius** [cursiveclojure/cursive#269]
Hi,

Two issues, one is that the synchronization of Lein project is slow and uncompleted after 30 mins, another issue is that  the removed module will be loaded again after a few seconds, I have to remove the related settings in the config fold under ~/.IdeaIC13.

Thanks for your efforts to cursive.

**Comment by cursiveclojure** [comment]
This option has been removed in the latest build of Cursive.
