### ISSUE TITLE
Rainbow parens not support for IDEA 13?

### ISSUE THREAD

**Issue by Renkai** [cursiveclojure/cursive#276]
I use IDEA 13 Ultimate with repository http://cursiveclojure.com/plugins-13.xml
There is rainbow  parens settings in Preference
![2014-02-13 13 22 59](https://f.cloud.github.com/assets/3381789/2157023/0ca3721c-9470-11e3-9c9f-983b94114a74.png)

but in the actual code there is no rainbow at all.
![2014-02-13 13 25 07](https://f.cloud.github.com/assets/3381789/2157027/33d4285e-9470-11e3-8ec3-097bb1a371f7.png)
------
It's because the rainbow parentheses is default off…

**Comment by cursiveclojure** [comment]
So I've just updated the rainbow parens with more vibrant colours for the next release. I've also fixed #496 which I think confused a lot of people. I'm going to close this now since AFAIK it should now be working in 0.1.58 - if not, please re-open.
