### ISSUE TITLE
Refactoring across lein local checkouts

### ISSUE THREAD

**Issue by savagematt** [cursiveclojure/cursive#280]
This isn't a very high priority feature- just adding it to the wishlist.

It would be incredibly cool if refactorings working across projects that are symlinked in the lein checkouts directory. IDEA (Cursive?) already recognises the dependency as a separate project.

**Comment by danielcompton** [comment]
I've been doing this successfully for quite some time now, I think this can be closed now?

**Comment by cursiveclojure** [comment]
I think so.
