### ISSUE TITLE
Should REPL tab(tool window) be able to rerun

### ISSUE THREAD

**Issue by weejulius** [cursiveclojure/cursive#283]
After shutdown the the repl, we need to close the tab and click the run again, can we have a button to rerun in the repl tab directly. another one is that the toggle of debug mode does not work.

**Comment by cprice404** [comment]
So what's the workflow on this?  You click the 'stop' button and then the 'reconnect' button?

Is there a button or action that will restart it all in one fell swoop?

**Comment by cursiveclojure** [comment]
Yeah, at the moment it's stop and reconnect. I could make the "reconnect" button a "restart" button and have that always be available?
