### ISSUE TITLE
Debugger doesn't stop at breakpoints after first Exception

### ISSUE THREAD

**Issue by deaddowney** [cursiveclojure/cursive#293]
I'm running some code through the Cursive REPL and the code is throwing an IllegalArgumentException.  It stops at my breakpoint before the Exception is thrown, but after that, if I try to rerun the same code, it doesn't hit my breakpoints.

**Comment by cursiveclojure** [comment]
So I couldn't reproduce this, but I just fixed a ton of debugger/breakpoint bugs. Please reopen this if you're still seeing it after 0.1.44 is released.
