### ISSUE TITLE
Support Prismatic Schema

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#319]
It would be nice if Cursive could "magically" recognize Prismatic Schema and it's variations on def and defn, etc.  Probably the same for core.typed.

**Comment by cursiveclojure** [comment]
This is finally fixed for the next build. `s/defrecord` is supported, and arglists etc are also supported correctly for all schema forms.

**Comment by cprice404** [comment]
Hooray!!!

**Comment by tonyvanriet** [comment]
Am I correct in thinking that `s/defmethod` is still not supported?
The parameters to the `s/defmethod` are all marked unresolved and the formatting behaves differently.

<img width="285" alt="cursive s-defmethod" src="https://cloud.githubusercontent.com/assets/306897/12868054/aade1de6-ccc3-11e5-8a8d-f4c13a6d9ddd.png">

**Comment by tonyvanriet** [comment]
I see #993 now. Looks like I'm not alone.
