### ISSUE TITLE
datomic.api resolved in REPL, but not in editor

### ISSUE THREAD

**Issue by vmarcinko** [cursiveclojure/cursive#326]
I have in my project.clj datomic-free dep:
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [com.datomic/datomic-free "0.9.4699"]]

But in editor I get complaint about datomic.api not being resolved:

(ns vmarcinko.zvonimir
  (:require [clojure.java.io :as io]
            [datomic.api :as d]))

Strangely, when I start REPL via default run configuration (setup up as "Run with Leiningen", everything is resolved properly there, so I can use auto-completion etc...

**Comment by gpellis** [comment]
Don't know if there was another reshuffle, but I'm currently getting a 404 on http://cursiveclojure.com/datomic-stubs-0.8.4218.jar.

**Comment by kernelp4nic** [comment]
@gpellis https://www.dropbox.com/s/r3dtuwkryf7ucmn/datomic-stubs-0.8.4218.jar?dl=0

**Comment by alexanderkiel** [comment]
Can be closed the current file is here: https://cursiveclojure.com/datomic-stubs-0.9.5153.jar

**Comment by kernelp4nic** [comment]
Yes! Thanks!

**Comment by danielcompton** [comment]
Looks like this one can be closed?

**Comment by cursiveclojure** [comment]
Right.
