### ISSUE TITLE
Cursive doesn't resolve 'bootstrap' macros import in Storm sources

### ISSUE THREAD

**Issue by dartwing** [cursiveclojure/cursive#374]
Hi guys,

Your awesome plugin doesn't resolve 'bootstrap' macros, which imports common usages throughout the code.

For example, please see here:
https://github.com/apache/incubator-storm/blob/master/storm-core/src/clj/backtype/storm/daemon/worker.clj

 (ns backtype.storm.daemon.worker
   (:use [backtype.storm.daemon common])
   (:use [backtype.storm bootstrap])
   (:require [backtype.storm.daemon [executor :as executor]])
   (:import [java.util.concurrent Executors])
   (:import [backtype.storm.messaging TransportFactory])
   (:import [backtype.storm.messaging IContext IConnection])
   (:gen-class))

  (bootstrap)

  (defmulti mk-suicide-fn cluster-mode)

Would you be able to support resolution of such macro in semi-automatic or even automatic way to get the full picture about included dependencies in given Clojure script?

Thanks,
Alex

**Comment by danielcompton** [comment]
Relates to #147, may be able to be closed.

**Comment by cursiveclojure** [comment]
Yes, between #147 and #328 this one is covered.
