### ISSUE TITLE
Dependencies from lein :user profiles are written to intellij iml files.

### ISSUE THREAD

**Issue by favila** [cursiveclojure/cursive#375]
Dependencies declared for a :user profile in leiningen show up in the IML generated by/for IntelliJ. This seems like the wrong thing to do.

IML files are often committed to a VCS (it also contains path settings, submodules, etc) because it makes it easier for others to get started with a project in IntelliJ. However if lein :user dependencies are included this file has the potential to change constantly depending on when a leiningen synchronize was last done.

There may be a reason I'm missing why this is necessary, though. (Maybe for the repl to fetch dependencies correctly?)

**Comment by cursiveclojure** [comment]
I'm going to close this since I think we decided that this was ok :)
