### ISSUE TITLE
NullPointerException when loading multiple projects with `:pedantic? :abort`

### ISSUE THREAD

**Issue by cprice404** [cursiveclojure/cursive#388]
I usually have several lein modules open in a single cursive project.  We use `:pedantic? :abort` on all of our projects.

Sometimes, when I have conflicting transitive dependencies, cursive prints out a reasonable error explaining what lein is upset about.  However, a lot of the time it just puts an NPE in the event log with no explanation.  I can usually figure out what's up by commenting out all of my dependencies and adding them back in a few at a time, but that's not my favorite thing in the world to do.

I'm sure that me just saying "I got an NPE!" without being able to give you a repro case (these are closed-source projects) or a stack trace doesn't make things too easy... any suggestions on where I can find some additional data to send along?

**Comment by cursiveclojure** [comment]
I believe this is fixed in the next build, but it's a difficult one to test. Let me know if the problem persists.

**Comment by jffry** [comment]
Awesome, thanks! I'll see if it still happens when `0.1.49` is out.

**Comment by jffry** [comment]
As of `0.1.49` and `0.1.50`, I now get the full error output from Leiningen about the conflicting versions, rather than a NullPointerException that crashes the plugin. Thanks for fixing this! :+1:

**Comment by cursiveclojure** [comment]
Oh great, thanks for letting me know!
