### ISSUE TITLE
Creation of remote REPL using leiningen conf is not possible

### ISSUE THREAD

**Issue by jeluard** [cursiveclojure/cursive#389]
If you do not provide details from the `Connect to server` section (both `Host` and `Port`) some validation prevents to use the `Use Leiningen REPL port` option. An error message is shown at the bottom of the screen stating `Run Configuration Error: Invalid host specified`.

Filling with dummy info solve the issue and the REPL is correctly created.

**Comment by jeluard** [comment]
This is fixed in latest cursive (`0.1.48`).

**Comment by cursiveclojure** [comment]
That's odd, I didn't think I'd fixed anything there - I'll take a look. Either way I'm planning to modify this code soon while adding new REPLs (CLJS!) so I'll get to it then if required.

**Comment by jeluard** [comment]
Oops you are right I was confused, I actually reused an old configuration with the workaround I suggested ..
Reopening just so that you can keep track of things and have the pleasure to close it yourself :)
