### ISSUE TITLE
Feature request: pp button in REPL

### ISSUE THREAD

**Issue by voj** [cursiveclojure/cursive#466]
I find myself typing (clojure.pprint/pp) several times a week. It would be awesome to have a button for that.

**Comment by sveri** [comment]
I'd also like this feature, pprinting a map relatively often.

**Comment by rutchkiwi** [comment]
+1

**Comment by cursiveclojure** [comment]
In the next build there is now an option (on by default) to automatically format values returned from the REPL. This should be very fast, even for large maps. There's an additional sub-option to split multi-line strings and align them if required.
