### ISSUE TITLE
paren tidy fails over comment line

### ISSUE THREAD

**Issue by coltnz** [cursiveclojure/cursive#479]
Its great how I can hit paren before the last parens and it pulls them to my last line of code condensing the whitespace. This doesn't work though with a comment on the last line.

Before
```
(
   |      ;
         )
```

After hitting ) with the cursor at  | 
```
(
         ;)
```

Expected

```
(
         );
```

**Comment by cursiveclojure** [comment]
This is fixed in the next build. However it doesn't pull the closing paren over the comment, you'll get this instead:
```
(a b c| ; comment
        )
```
->
```
(a b c ; comment
  )|
```
