### ISSUE TITLE
feature request: apply different color for errors in local namespaces

### ISSUE THREAD

**Issue by wilkerlucio** [cursiveclojure/cursive#499]
Hi,

Doing some debugging here I'm finding that sometimes is very difficult in a long stack to find the calls that happens on my local namespaces.

Would be great if you detect local namespaces (those that are not on dependencies) and put a different color on those, I think that would greatly improve the agility when trying to find the error on the stack.

**Comment by cursiveclojure** [comment]
This is fixed in the next build, using code folding. Stack traces are prettified to their Clojure meanings, and trace elements from outside the project are folded by default.
