### ISSUE TITLE
"Sync files in REPL" also loads Clojurescript files in Clojure REPL

### ISSUE THREAD

**Issue by mtruyens** [cursiveclojure/cursive#506]
I have a project where there are separate CLJ / CLJS / CLJX folders. When I am in a Clojure REPL and try to sync a .clj file, IntelliJ also tries to load one or more files from the CLJS folder -- obviously resulting in errors because many Clojurescript forms are not supported by Clojure.

**Comment by bilus** [comment]
Same thing here (with cljx but the .cljs file causing trouble isn't generated nor does it share namespace name with a .clj). 

All it takes is have `:source-paths ["src/cljx" "src/clj" "src/cljs"]`. If I remove the last string from the vector, it all works (but deploys are broken).
