### ISSUE TITLE
Cursive not resolving all parameters on a Compojure defroute

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#530]
Suppose you have the following trivial defroute in Compojure:

    (defroutes home-routes
      (GET "/" [] (home))
      (POST "/" [name message] (save-message name message)))

On the POST definition, _name_ gets resolved, but _message_ does not.

![screen shot 2014-10-08 at 9 25 53 am](https://cloud.githubusercontent.com/assets/31263/4554770/0a72964a-4eb4-11e4-858b-213f4ea498af.png)

**Comment by kernelp4nic** [comment]
Any news about this? Thanks!

**Comment by cursiveclojure** [comment]
This should be fixed in the latest Cursive build (0.1.54).

**Comment by kernelp4nic** [comment]
Awesome!
