### ISSUE TITLE
Code Style options display issues on IntelliJ 12

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#539]
There are several display issues when viewing the Code Style options for Clojure on IntelliJ 12.  These range from apparently the default width being too small for the frame:

![image](https://cloud.githubusercontent.com/assets/31263/4625482/e6419c04-5376-11e4-80e7-489da86e6e22.png)

To displaying empty rows beyond the horizontal scrollbar:

![screen shot 2014-10-14 at 10 49 13 am](https://cloud.githubusercontent.com/assets/31263/4625495/143e8c48-5377-11e4-85cd-4837ce6c0dce.png)

To the display getting out of what as you scroll:

![screen shot 2014-10-14 at 10 51 05 am](https://cloud.githubusercontent.com/assets/31263/4625507/23af0a22-5377-11e4-9fbb-24ac07a6ee10.png)

Not sure if these are IntelliJ issues or Cursive ones, thought about filing it just in case.

**Comment by cursiveclojure** [comment]
The first two issues are fixed in the next build.
