### ISSUE TITLE
Consider making double-clicking on a word extends accross dashes

### ISSUE THREAD

**Issue by JeffHeon** [cursiveclojure/cursive#55]
E.G. double-clicking on the 'fib' part of a var named 'not-fib' selects the whole name.

Since dashes are so commonly used in var names in Clojure, I think it would be handy.

**Comment by lewisl9029** [comment]
@cursive-ide Any chance you could consider making this behavior optional? Literally every other editor I've ever used stops selection at dashes when double clicking, and I rely on this constantly when using multiple cursors, for instance. I switch between languages and editors often, and Cursive has been great for Clojure so far, but this is the one thing that's seriously throwing me off.

Maybe there is already an option to change this behavior and I just didn't look in the right place? If that's the case I'd appreciate it if you could point me to the option. Thanks!
