### ISSUE TITLE
Cursive doesn't recognize dependencies with classifiers (e.g. test jars)

### ISSUE THREAD

**Issue by cprice404** [cursiveclojure/cursive#558]
In some of our library projects, we have test utility code that is useful for downstream projects to depend on, but doesn't really make any sense to include in a production jar.  To achieve this, we use maven/lein "classifiers" to have those projects build multiple jars (e.g. 1 production jar, 1 test jar).  Then in the downstream projects we can specify a dependency on the test jar in the `:dev` profile, so that the test jar is available at test time but is not in the production classpath.

This all works fine from the CLI and works fine in Cursive's `lein` repl, since `lein` understands the "classifier".  Cursive does not seem to recognize it, though, so the "test" jar does not show up in IDEA's list of the project dependencies.

Example of creating a test jar:

https://github.com/puppetlabs/clj-kitchensink/blob/master/project.clj#L32

Example of consuming it in a downstream project:

https://github.com/puppetlabs/trapperkeeper/blob/master/project.clj#L41

**Comment by chrisbetz** [comment]
+1

**Comment by cprice404** [comment]
A side effect of this that we've noticed recently is that there is no way to get to the 'indentation' dialogue in the GUI.  So, macros that we have in our test jars are marked by Cursive as unrecognized / compile errors, and there is no way to tell it to indent them like a macro... so any time you do any major refactoring inside the body of one of these, Cursive re-indents everything over way too far to the right.

Our 'kitchensink' project on clojars has a test jar if you need an example:

https://clojars.org/puppetlabs/kitchensink
https://github.com/puppetlabs/clj-kitchensink#using-our-test-utils

Here's a macro that it contains that would illustrate the issues if you use it in a test:

https://github.com/puppetlabs/clj-kitchensink/blob/f620e5acabad78bd80a649e76925c4cdd043feae/test/puppetlabs/kitchensink/testutils.clj#L26-L29

**Comment by cursiveclojure** [comment]
Ugh, that sounds bad. Thanks for the reproduction case, I'll try to fix this shortly.

**Comment by cursiveclojure** [comment]
This is fixed for the next build. Cursive rather over-enthusiastically excluded any jars with classifiers, to avoid creating libs for source and javadoc dependencies. These are now excluded specifically, and anything with a `test` classifier is assigned to the module with a Test scope. Let me know if this produces any unexpected consequences - I'm not sure what else classifiers might be used for.

**Comment by cprice404** [comment]
hooray!  will keep an eye out.

**Comment by cprice404** [comment]
I may have spoken too soon on this one :(

I've seen this change do what I'd expect in some projects.  However, on a project I started working on this morning, something's going wrong.  It seems that IDEA is now *only* seeing the test jar for libraries that have one; if I leaf through the 'External Libraries' tree I can get to, e.g. `puppetlabs/kitchensink:1.0.0`, and underneath there there is only the test jar.  So now cursive is highlighting/indenting the functions / macros from the test jar properly, but it's marking all of the stuff from the *real* library as "cannot be resolved" :(

Any ideas?  Should I open a new issue?

**Comment by cursiveclojure** [comment]
I'll take a look and see if I can reproduce this - is there anything unusual about the project where it doesn't work?

**Comment by cursiveclojure** [comment]
So I can't see anything in the code that should cause this. But I was thinking about profiles, which have changed in 2.5.1 - is the problematic project doing anything strange with profiles that might cause this?

**Comment by cprice404** [comment]
I'll see if I can put together a simple project.clj that repros and let you know.

**Comment by cprice404** [comment]
@cursiveclojure so yeah it may have to do with profiles; we always specify the test jars as a dependency in our `dev` profile, so they're on the classpath for testing, but don't get included in our uberjar.

Here's a simple repro case:

https://github.com/cprice404/cursive-testjar-test

If you open that up in cursive and then go look at the single test namespace, you should see that it's recognizing the stuff from the testutils namespace (from test jar) but not the stuff from the production namespace.

Let me know if you'd prefer to start up a new github issue for this.  And if it ends up being something in leiningen we might be able to help work on a PR for them.

**Comment by mruzicka** [comment]
**An observation**: Both [kitchensink-1.0.0.jar](https://clojars.org/repo/puppetlabs/kitchensink/1.0.0/kitchensink-1.0.0.jar) and [kitchensink-1.0.0-test.jar](https://clojars.org/repo/puppetlabs/kitchensink/1.0.0/kitchensink-1.0.0-test.jar) - which are declared as dependencies in @cprice404's test project - include an identical ```project.clj``` file - i.e. both define the same leiningen project:
```clojure
(defproject puppetlabs/kitchensink "1.0.0"
...
```

**A hypothesis**: Given that I can only see that project listed once as a dependency in the IntelliJ's *Project* tool window (and when I expand that entry I can see that it references only the ```kitchensink-1.0.0-test.jar``` jar file), could that be related to the fact that cursive is unable to resolve symbols from both of the jar files at the same time?
