### ISSUE TITLE
Partial project import with Cursive 0.1.40 and IntelliJ 12

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#569]
1) Clone https://github.com/Skinney/coc-helper.git
2) Import project.clj
3) Cursive will only add the src/cljx and src/styles folders, disregarding src/clj and src/cljs

![screen shot 2014-10-24 at 11 05 13 am](https://cloud.githubusercontent.com/assets/31263/4766709/cb15a4b2-5b54-11e4-96b6-2648aab9c89a.png)

I don't see any errors logged. Tried this twice from a clean repo and got the same result.

**Comment by cursiveclojure** [comment]
This is fixed in 0.1.64.
