### ISSUE TITLE
Leiningen :local-repo relative path resolves to IDEA bin directory

### ISSUE THREAD

**Issue by shinych** [cursiveclojure/cursive#572]
Having told the leiningen project to use local repo:

    (defproject 
      ;....
      :local-repo "m2repo"
    )

I expect that all the dependencies will be installed into the [project.dir]/m2repo. 

This of course works when I start lein from a command-line being in the [project.dir] directory. 
However when the very same project is being loaded into Cursive, the expected local m2repo is created within IDEA bin directory (/Applications/IntelliJ IDEA 13 CE.app/Contents/bin at my machine).

**Comment by danielcompton** [comment]
Relates to #333.
