### ISSUE TITLE
Leiningen local repo from :repositories resolves to IDEA bin directory 

### ISSUE THREAD

**Issue by shinych** [cursiveclojure/cursive#573]
Having configured the leiningen project like this:
```
(defproject 
        ;...
        :repositories {
                 "local" ~(str (.toURL (java.io.File. "m2repo")))
        }
        ;...
    )
```

I expect that the dependencies will additionally be looked up from the [project.dir]/m2repo.

This of course works when I start lein from a command-line being in the directory.

However when the very same project is being loaded into Cursive, the (java.io.File. "m2repo") resolves to the IDEA bin directory (/Applications/IntelliJ IDEA 13 CE.app/Contents/bin at my machine). This leads to the fact that the necessary jars deployed locally are not found.

This goes together with the issue https://github.com/cursiveclojure/cursive/issues/572

**Comment by conan** [comment]
Am I right in assuming this is closed as WONTFIX? It would be useful to know whether I have to put in some effort to reconfigure the build to work with Cursive, but if it's planned to be fixed then maybe we can workaround until then.

**Comment by cursive-ide** [comment]
@conan I believe this should work now. This was closed before the Great Leiningen Refactor. The one thing that won't work is `(File. "m2repo")` since there's no way to hook that, but if you do `(clojure.java.io/file "m2repo")` this should work correctly.

**Comment by conan** [comment]
I can confirm that's working perfectly in cursive, from the command line and in Heroku magic-land.

**Comment by cursive-ide** [comment]
Oh great, thanks for letting me know!

Actually, an inspection for `File` constructors in `project.clj` would be awesome, now that I think about it.

**Comment by conan** [comment]
Hmm, I'm experiencing a problem updating a local repo now.  Defined in the same way, I now get an error saying `Resource nexus-maven-repository-index.properties does not exist` when I press the Update button in the Maven repositories settings.

**Comment by cursive-ide** [comment]
I don't think that's a Cursive problem - at that point it's all IntelliJ. I don't know why this might have changed - have you just upgraded anything?

**Comment by conan** [comment]
Yes, everything!

**Comment by conan** [comment]
It seems cursive is incorrectly listing the repo as a Remote repo - is there a way of changing this?
