### ISSUE TITLE
starting a new comment by typing the ';' character should generate an undo point

### ISSUE THREAD

**Issue by sfnelson** [cursiveclojure/cursive#583]
While typing clojure it is easy to type ';' accidentally, for example instead of ':' when attempting to input a keyword. When this happens, cursive will indent the current line to the default comment position (e.g. 80 characters). This makes it hard for the user to correct the mistake as backspace will return them to column 79 but undo will revert more typing than just the ';' character.

To alleviate this issue, I suggest generating an undo point whenever a comment is started. Alternatives would include backspace on a comment ';' symbol trimming whitespace and returning the cursor to the previous non-whitespace character.

**Comment by sfnelson** [comment]
This issue has regressed at some point in the last few versions.

**Comment by cursive-ide** [comment]
One thing that has changed in the last version (due to parinfer) is that paredit mode is no longer on by default. This feature required paredit mode to be on, do you have this enabled?

**Comment by sfnelson** [comment]
Yes, I couldn't write clojure without paredit :-)

The regression occurred some time ago but I haven't reported it until now.

**Comment by sfnelson** [comment]
I should be specific, the regression is that when you hit `;` while typing your cursor moves significantly such that a single backspace is not sufficient to undo the change, and the built-in undo functionality will undo more than the cursor movement, e.g. when typing a map destructuring you lose all your typing instead of just the comment.
