### ISSUE TITLE
Debug REPL session doesn't stop on breakpoint

### ISSUE THREAD

**Issue by aeberts** [cursiveclojure/cursive#617]
Caveat: This issue may be due to the fact I don't fully understand how the debug repl works :-) 

I have a "Local Repl" config setup as per: https://cursiveclojure.com/userguide/repl.html

I have set a breakpoint in a function: 

```
(defn testdebug [foo]
  (println foo))            ;; <---  breakpoint set here in intellij
```

- I have the Local Repl config selected and I click the green bug in the toolbar: (Debug 'Local Repl')

- I call the function from the Repl that contains the breakpoint:

```
(offline-4clojure.p97/testdebug "blah")
blah
=> nil
```

...The repl returns the value and doesn't pause execution at the breakpoint.

expected: Cursive would pause execution at the breakpoint and allow me to debug the function. 

Maybe I'm missing something obvious here??

**Comment by leonardoborges** [comment]
I'm on IntelliJ 14 as well and having similar issues. I tried it on 13 as well and it is a bit unstable. First time using it worked fine. Then restarted the debugger but the breakpoints would no longer work - the red circle in the editor has an 'x' inside it with the message: warning no executable code found at line `n`

**Comment by stijnopheide** [comment]
I'm seeing the same problem in both IntelliJ 13.1.6 and 14.0.2, Cursive 0.1.43, although the 'Load file in Repl' suggestion from @aeberts doesn't work either.

Once you do a require of the namespace in the debug REPL (or Load file in REPL), the breakpoint gets a cross with the message: warning no executable code found.

**Comment by cursiveclojure** [comment]
Yeah, this is definitely flaky. I'm going to look at this soon since I use the debugger all the time and I really need it to work on v14. After loading the file in the REPL, I sometimes find that removing and replacing the breakpoint helps IntelliJ figure it out, but it's not reliable.

**Comment by dhoff1985** [comment]
This may actually be an issue with cursive 0.1.43. Using idea 14 and cursive 0.1.43 I was unable to stop at breakpoints. I downgraded Intellij first and still saw the issue. Then I tried downgrading cursive. Cursive 0.1.42 stops at breakpoints in both 13 and 14.

**Comment by cursiveclojure** [comment]
Yes, it's looking like this is a regression in 0.1.43 related to the namespace support which got a major upgrade. I'll fix this, and see if I can figure out why it's flaky in general with v14 at the same time.

**Comment by cursiveclojure** [comment]
Curiously enough, this seems to be working better for me in 0.1.43 than in earlier builds, but several people have reported the opposite. I'll see if I can figure out what's going on.

**Comment by cursiveclojure** [comment]
So I went over this code (it's legacy code from La Clojure which I haven't kept up to date with Cursive improvements), and frankly it's amazing that the debugger ever stopped at all. Many bugs fixed, including:
* Better class matching over the JDI, should make the debugger faster and allow stopping in `fn` forms and forms that desugar to it. Previously this didn't work.
* Better matching of debug positions to file positions (see #168)
* Better REPL handling. Previously forms entered in the REPL could never be debugged, because their source and line information was wrong. This makes sense in the case of functions entered in the REPL editor (since there really is no source to debug over) but was a bit unfortunate when executing forms from the editor with e.g. Send top form to REPL. These now work as you would expect and the updated versions can be debugged.

**Comment by leonardoborges** [comment]
Hey Colin this is amazing!  What's the easiest way to try out these fixes? :)

**Comment by cursiveclojure** [comment]
Patience, grasshopper :-). They'll be in the next build. I'm looking into fixing expression evaluation and a few other things while I'm at it, I'll test it a bit and then I'll put a debug build up so you can kick the tyres a bit.

**Comment by leonardoborges** [comment]
hahah sorry. Can't contain my excitement :)  Looking forward to it!

**Comment by aeberts** [comment]
Great news! Please let me know if you'd like help testing this (or other) changes.

**Comment by cocodrino** [comment]
Hi guys, is it fixed? I'm using the latest idea and cursive plugin (cursive-14-0.1.44) and seems not respect the breakpoints, also the remote debug is not working at all (it connects but doesnt stop in the breakpoints neither) thanks...

**Comment by aeberts** [comment]
Debugging works for me and is pretty stable on the following config:

* Cursive: cursive-14.0.1.45  <--- note to cocodrino: this is a newer build than you're using
* Intellij 14.0.3
* Mac OS 10.9.5

Hope that helps.

**Comment by cocodrino** [comment]
thanks for the answer @aeberts ..I've updated to the latest version (xxx.46 now!!) and seems works now...I'm still need check the remote debugger too (I tried it with the xxx.44 version and it didnt works...)

Something weird, the first time than I ran it, when I load my code in the repl using "run top form in the repl" the code fails with (fn is not defined  or "defn" is not defined)

;; load this function directly in the repl fails
(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
CompilerException java.lang.RuntimeException: Unable to resolve symbol: defn in this context....

I needed load the whole file in the repl (using "Load file in the repl") and this seems start working good..

;;typing in the repl
((fn [m] (println "hello " m) ) "debug")
hello  debug

I need check the remote debugger now....

**Comment by cursiveclojure** [comment]
Your problem with the `defn` is that when you execute code from the editor in the REPL, by default it executes the code in the namespace of the editor file, not the REPL. This error means that you haven't loaded that namespace into the REPL yet, which is why it works after loading the entire file.
