### ISSUE TITLE
src directories excluded after Run REPL

### ISSUE THREAD

**Issue by rogergl** [cursiveclojure/cursive#622]
The source directories of my project get excluded as soon as I run a lcoal repl.

The project looks like this:

<pre>
(defproject om-p "0.1.0-SNAPSHOT"
            :description "FIXME: write this!"
            :url "http://example.com/FIXME"

            :dependencies [[org.clojure/clojure "1.7.0-alpha4"]
                           [org.clojure/clojurescript "0.0-2371"]
                           [clojurewerkz/spyglass "1.0.0"]
                           [markdown-clj "0.9.47"]
                           [secretary "1.2.0"]
                           [ring-server "0.3.1"]
                           [ring "1.3.0"]
                           [lamina "0.5.2"]
                           [compojure "1.1.8"]
                           [hickory "0.5.3"]
                           [domina "1.0.3-SNAPSHOT"]
                           [cljs-ajax "0.3.3"]
                           [enlive "1.1.5"]
                           [aleph "0.3.2"]
                           [korma "0.3.0"]
                           [com.taoensso/carmine "2.7.1"]
                           [mysql/mysql-connector-java "5.1.30"]
                           [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                           [om "0.7.3"]]

            :plugins [[lein-cljsbuild "1.0.3"]
                      [com.keminglabs/cljx "0.4.0"]
                      [com.cemerick/clojurescript.test "0.3.1"]]

            :source-paths ["src/cljs" "src/clj"]

            :cljx {:builds [{:source-paths ["src/cljx"]
                             :output-path "src/clj"
                             :rules :clj}

                            {:source-paths ["src/cljx"]
                             :output-path "src/cljs"
                             :rules :cljs}]}

            :cljsbuild {
                        :builds [

                                 {:id "ct"
                                  :source-paths ["src/cljs" "src/projects/ct"]
                                  :compiler {
                                             :output-to "resources/public/js/om_p.js"
                                             :output-dir "resources/public/js/ct/out"
                                             :optimizations :none
                                             :source-map true}}

                                 {:id "nosql"
                                  :source-paths ["src/cljs" "src/projects/nosql"]
                                  :compiler {
                                             :output-to "resources/public/js/om_p.js"
                                             :output-dir "resources/public/js/nosql/out"
                                             :optimizations :none
                                             :source-map true}}

                                 ]})</pre>

**Comment by danielcompton** [comment]
I think this can be closed now?

**Comment by cursiveclojure** [comment]
I think so, yes.
