### ISSUE TITLE
Don't wrap clojure.test actual fail value in ()

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#625]
The expected vs. actual values here make it look like I was returning a list with the value 1, when I was just returning 1. Could you remove the ()'s around the Actual value? Or is there a reason why it's done that way?

![screenshot of intellij idea 17-11-14 6 18 25 pm](https://cloud.githubusercontent.com/assets/811954/5065505/39e37b32-6e86-11e4-9588-81642bbb919b.png)

**Comment by yatesco** [comment]
+1 - I burned a few hours banging my head against the wall whilst debugging a particularly complicated set of nested data structures trying to figure out why it was being wrapped in a list :).

**Comment by danielcompton** [comment]
I know you've got heaps of worthy bugs and features to implement, but would I be able to request this one? Are bribes accepted? :)

**Comment by cursiveclojure** [comment]
So I can't reproduce this. Is there anything specific that seems to provoke this? I've tried various combinations:

![screen shot 2015-07-08 at 12 52 11 am](https://cloud.githubusercontent.com/assets/5589171/8559297/c56a0d1a-250b-11e5-8c62-5bb0f052b4f9.png)

![screen shot 2015-07-08 at 12 52 48 am](https://cloud.githubusercontent.com/assets/5589171/8559298/c573dd54-250b-11e5-9141-29b67c2d4ea4.png)

![screen shot 2015-07-08 at 12 53 08 am](https://cloud.githubusercontent.com/assets/5589171/8559299/c57c8f76-250b-11e5-9228-4fc31ba88735.png)

Interestingly, note that the expected and actual values are totally different, i.e. I see the actual expressions. Are you doing anything strange with your test running? Using humane output or anything like that?

**Comment by danielcompton** [comment]
The plot thickens... I was using Humane output, but the same behaviour happens even when I completely remove my ~/.lein/profiles.clj.

**Comment by cursiveclojure** [comment]
Do you get this in an open project I can look at?

**Comment by danielcompton** [comment]
I can reproduce this by running

```
lein new mytest
```

opening it in Cursive, and running the (single failing) test.

**Comment by cursiveclojure** [comment]
What I meant was, is the project open source so I can try to reproduce what you're seeing?

**Comment by danielcompton** [comment]
It happens on any project. The minimal case is a blank lein app though.

**Comment by cursiveclojure** [comment]
That's exactly how I tried to test it. Cursive monkey-patches clojure.test quite heavily to do its thing, so if you have anything else (like humane output etc) that might break it.

**Comment by yatesco** [comment]
I was using humane output at the time, that might be it.

**Comment by danielcompton** [comment]
I'm pretty sure it was Humane test output that was the issue. I was confused when debugging this because Leiningen had memoized my profile.clj so it wasn't picking up the changes.
