### ISSUE TITLE
cursive breaks vim plugin on intellij 14 (but not 13)

### ISSUE THREAD

**Issue by ajmorgan** [cursiveclojure/cursive#634]
the "in" and "around" vim commands are broken after installing cursive on intellij 14 (whereas 13 works great)

example broken commands (when in the vim command mode)
change in s-expression:  ci(
change around s-expression:  ca(
highlight whole s-expression:  va(
change in vector:  ci[
change in string:   ci"
etc.

example usage:
with the cursor somewhere in the following s-expression
(ns loot-collector.collector)
I expect the change in command  ci(
to leave me in insert mode inside empty parens
()

currently, in Intellij 14, using the 'ci(' command, I get something that looks like
(ns loot-coll () ector.collector)

Hope this helps, and thanks for the great product,
Adam

**Comment by ajmorgan** [comment]
This issue is fixed in 0.1.49

**Comment by cursiveclojure** [comment]
How very strange - I'm pleased, but I have no idea why! Thanks for the report.
