### ISSUE TITLE
Strange formatting problem

### ISSUE THREAD

**Issue by rogergl** [cursiveclojure/cursive#639]
I get

<pre>
(defn do-alot []
              (exec-raw ["delete from user_session_data"])
              (let [result (map store-test-data (range 0 50000))
                    resolve (map (fn [e] @e) result)
                    cnt (count (filter (fn [e] (= e true)) resolve))]
                  cnt))
</pre>

but I would expect to get

<pre>
(defn do-alot[]
      (exec-raw ["delete from user_session_data"])
      (let [result (map store-test-data (range 0 50000))
          resolve (map  (fn[e] @e) result)
          cnt (count (filter (fn [e] (= e true)) resolve))]
        cnt))
</pre>

This started to happen with 0.1.41
BTW:  Sometimes it produces the desired output, sometimes not.

**Comment by cursiveclojure** [comment]
I'm going to close this - if this is still a problem for you, please re-open.
