### ISSUE TITLE
Java functions cannot be resolved

### ISSUE THREAD

**Issue by fatlazycat** [cursiveclojure/cursive#640]
Sure this is probably reported elsewhere though can't see it offhand.

![ember library mediator](https://cloud.githubusercontent.com/assets/338975/5096886/06843dec-6f6e-11e4-9f00-535221662cd8.png)

Various java functions are reporting as unresolved, this from java.o.File. The class isn't imported. If I import it then the 'cannot be resolved' issue goes away I then get an unused import issue.

Code runs fine.

**Comment by cursiveclojure** [comment]
The original problem reported by @fatlazycat is fixed in the next build - Cursive now has type inference. However the specific case in your example won't work, because Clojure's type inference isn't smart enough to propagate type hints for `apply` - this means that Clojure itself would give you a reflection warning in that case. But that case would work if you hadn't used apply, or if you had type hinted the apply invocation.

**Comment by fatlazycat** [comment]
Hi, has this come back ?

If I attempt to use from java.io.File .isDirectory I get a warning that it cannot be resolved, but code runs fine.
If I (:import java.io.File) that warning goes to be replaced by one that states the import is being used.

I;m doing something wrong ?

**Comment by Wegi** [comment]
I also recently get the same bug, that java interop calls are suddenly not correctly found by cursive.

**Comment by cursive-ide** [comment]
@Wegi Can you show a screenshot of what you're seeing?

@fatlazycat Sorry, I missed your earlier comment - is this still a problem for you?

**Comment by Wegi** [comment]
Sure! I had a similar problem with calling .getTime - but there i thought it would just be type inferece. But here the class is clearly indicated. Even Integer/parseInt is not recognized for some reason.
![Bildschirmfoto von 2020-07-09 13-10-21](https://user-images.githubusercontent.com/1516122/87032940-a77ed480-c1e5-11ea-8098-72782e467a06.png)

**Comment by sauvala** [comment]
Hi 👋 just reporting that I'm seeing similar behaviour as @fatlazycat and @Wegi.
<img width="866" alt="Screenshot 2020-07-10 at 1 27 22" src="https://user-images.githubusercontent.com/4200280/87096925-9b7a2d80-c24c-11ea-87d1-c7c72d0bbd13.png">

**Comment by cursive-ide** [comment]
@Wegi The problem there is that that function is not valid Clojure - the dot-constructor form needs to be an invocation, like:
```
(defn now [] (java.util.Date.))
```
If you take the trailing dot off, it will resolve correctly since `java.util.Date` refers to the class, but won't do what you want.

**Comment by cursive-ide** [comment]
@sauvala Thanks for the example. Here's a list of things to check:

1.  The first thing to check is that you have a JDK configured for your module. Go to _File | Project Structure_, then choose _Modules_ and check your module has a JDK. If your module delegates to the project JDK you can check that is configured correctly in the _Project_ section. This can become misconfigured when you update IntelliJ, for example if you just updated to 2020.2. This is the most likely culprit in your case where normal symbols resolve correctly
2. Next, check that your project has imported correctly. Open the Lein/Deps toolwindow and check that you see your project there. If it's not, then right click on the `project.clj` or `deps.edn` in the Project toolwindow and choose "Add as Lein/Deps project".
3. With weird things like this, the next thing to try is _File | Invalidate Caches / Restart_. Sometimes the indexes can become corrupted and that will fix them.

Let me know how that goes!

**Comment by sauvala** [comment]
@cursive-ide Thanks Colin! The 1st check in the _Project Structure_ fixed my problem. I think I had mismatched JDK-versions in the _Project_ and _Modules_  -sections. When I switched them to be the same version the IDE was able to resolve the calls. 🎉 It could have been an update in the IntelliJ that messed up with the configs. Good to know where to check if this happens again.

**Comment by fatlazycat** [comment]
I don't have that project anymore but would seem reasonable as the same solution. Thanks
