### ISSUE TITLE
cemerick.cljs.test macros are not recognised

### ISSUE THREAD

**Issue by yatesco** [cursiveclojure/cursive#654]
Hi,

None of the macros in the following namespace declaration are recognised:

```(ns health.ui.page.patients_test
  (:require-macros [cemerick.cljs.test
                    :refer (is deftest with-test run-tests testing test-var)])
  (:require [cemerick.cljs.test]
            [health.ui.page.patients :refer [determine-actions]]))
```

Everything works (i.e. the tests are actually executed by `lein cljsbuild test`) so I don't think there is a local problem (but this scenario works in other files).

**Comment by danielcompton** [comment]
Quite likely relates to #147.

**Comment by cursiveclojure** [comment]
And #917. I'm probably only going to add support for `cljs.test`, so the macros should all be recognised now. Getting the test functionality to work as with `clojure.test` requires a better CLJS REPL integration.

**Comment by cursiveclojure** [comment]
I'm going to close this since I won't be supporting cemerick's test lib now that `cljs.test` is official.
