### ISSUE TITLE
No indent options for defmulti

### ISSUE THREAD

**Issue by dustinconrad** [cursiveclojure/cursive#661]
In Preferences > Code Style > Clojure > Form Parameters there is no option to change the indentation rules for defmulti.

Additionally, none of the entries is searchable, making it difficult for me to determine if this is user error or not.

**Comment by cursiveclojure** [comment]
I just checked this, and it appears that the defaults for defmulti are ok, or at least agree with what Emacs does. If you want to customise them, you can do so following the instructions [here](https://cursiveclojure.com/userguide/formatting.html). Let me know if this doesn't do what you want.
