### ISSUE TITLE
Dependency cycle for cljx project

### ISSUE THREAD

**Issue by bilus** [cursiveclojure/cursive#693]
Hi,

First of all, thank you so much for an excellent plugin; I'm totally addicted and I hope I can make it work since the workflow (when there are no issues) is simply amazing compared to other environments.

I know you must hate cljx-related issues but I'm totally stuck having spent a better part of the evening and night trying to get things to work.

My project uses cljx and I'm unable to use the repl. I created a branch for this problem:

https://github.com/bilus/om-event-bus/tree/cursive-issue-2

(There's also https://github.com/bilus/om-event-bus/tree/cursive-issue but cursive-issue-2 is a close approximation of https://github.com/lynaghk/cljx/blob/master/sample.project.clj and seems to work slightly better.)

Here are the steps to recreate the issue:

1. Open REPL.
2. Open impl_test.clj and run Tools > REPL > Run tests in current NS in REPL.
    
    **Tests pass, here's what you should see in the REPL window:**
    ```
    Loading test/om_event_bus/impl_test.clj... done
    Running tests in om-event-bus.impl-test
    Ran 8 tests containing 19 assertions.
    No failures.
    ```
3. Change src/cljx/om_event_bus/impl.cljx

4. Run Tools > REPL > Sync files in REPL

    **It shows a "Dependency cycle impl.cljx -> impl.cljx" popup.**

5. Run Tools > REPL > Run tests in current NS in REPL.

    **It fails now:**
    ```
    Loading src/cljx/om_event_bus/impl.cljx... done
    CompilerException java.lang.RuntimeException: No reader function for tag +clj, compiling:    (/Users/martinb/dev/Logoot/om-event-bus/src/cljx/om_event_bus/impl.cljx:3:44) 
    ```

I'm using IntelliJ 14.0.2 with Cursive 0.1.43

Please try recreating the problem. Perhaps there's something wrong with my project.clj but I've tried everything I could think of. If there is _any_ workaround at all, I'll be willing to try it.

Thank you so much in advance.

**Comment by bilus** [comment]
UPDATE: Just in case it helps, Cursive 0.1.42 exhibits the same behavior.

**Comment by cursiveclojure** [comment]
Interesting - thanks for the very detailed report. I'll try to look at this tomorrow.

**Comment by bilus** [comment]
Thanks! FYI, I've just fixed the mixed up numbering of steps; it had been a very busy day for me.

**Comment by ikitommi** [comment]
having the same problems here.

**Comment by cursiveclojure** [comment]
This is interesting - it's because the file is require-macros'ing itself. I'll fix this for the next build. Thanks again for the great reproduction case, it made this very easy to find.

**Comment by cursiveclojure** [comment]
This is fixed for the next build. Note that the problem in your step 5 is unrelated - you're running the tests in the wrong NS there. If you want to re-run the previous tests you'd need 'Re-run last test action in REPL' or switch to your test NS and run from there.
