### ISSUE TITLE
Live Templates don't work in CLJS

### ISSUE THREAD

**Issue by cursiveclojure** [cursiveclojure/cursive#700]
We should create a ClojureScript context and add the existing templates to it.

**Comment by aeberts** [comment]
I'm not sure if I'm looking in the right place but I do not see the ClojureScript context or templates:

Versions:
Intellij 14.0.3
Cursive 0.1.44

Going to:
Preferences -> Editor -> Live Templates

...Shows a context for Clojure but none for ClojureScript. (see attached image). I tried loading a ClojureScript project to see if that revealed the context but it did not.

**Comment by cursiveclojure** [comment]
No, the Clojure context encompasses Clojure, ClojureScript and CLJX. I considered making separate contexts for them but decided that this would be simpler. Arguments welcome if there's a need to have them separated, though.

**Comment by aeberts** [comment]
That totally makes sense - there's so much overlap having separate contexts would mean lots of unnecessary duplication. I verified that Live Templates work on my setup in a CLJS file. Thx!

**Comment by kernelp4nic** [comment]
I'm sure this is the simpler solution... but for me it makes more sense to have a ClojureScript context separately. (and also make sense some templates work for both contexts)

I have a lot of om-related templates, sablono templates, print fn, that makes noise when I'm working on clj files.

The most easy example is the `log` template. `console.log` for cljs and `clojure.tools.logging` for clj.

I don't know intellij internals, but there is no way to define a custom context?
