### ISSUE TITLE
Error when launching IntelliJ

### ISSUE THREAD

**Issue by richtera** [cursiveclojure/cursive#702]
Curious, but IntelliJ is complaining about the following file:
Error while indexing /usr/local/lib/python2.7/site-packages/django/contrib/gis/templates/gis/admin/openlayers.js
1. It's within python libraries... not sure why IntelliJ says that Cursive is causing the error.
2. It's a javascript file inside of a python library and should probably be ignored anyways.
3. Not sure what to do about this, but it comes up every time I launch
Thanks
Andy

**Comment by cursiveclojure** [comment]
This problem was caused by Cursive indexing the JavaScript files for its ClojureScript support. This was actually fixed a couple of releases ago (0.1.46).
