### ISSUE TITLE
[0.1.43] Class imports use list, not vector (regression) 

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#703]
Despite my configuration, which enabled vectors for class imports, the imports occur using parens.

This occurs in namespaces that have existing imports (using square brackets) and in namespaces that do not.  I've just upgraded from IntelliJ13 to 14 and still see the same behavior.

**Comment by cursiveclojure** [comment]
Yes, my apologies about this - this was fixed in the last drop (0.1.47).
