### ISSUE TITLE
REPL soft wraps is slow for long lines

### ISSUE THREAD

**Issue by lucascs** [cursiveclojure/cursive#704]
Hey =),

when I turn on soft wraps for the REPL panel and there is some command that outputs a long line (> 1k columns), it freezes IntelliJ for several seconds (some times minutes), and when it responds again it keeps being very slow until I clean the output and turn off soft wraps.

sometimes even without soft wraps, if there is a really long line (> 10k columns) and it is on the screen, the REPL panel also gets slow.

IntelliJ 14.0.2

Thanks

**Comment by danielcompton** [comment]
Relates to #514.
