### ISSUE TITLE
Typing curly brackets inside string doesn't work

### ISSUE THREAD

**Issue by immoh** [cursiveclojure/cursive#707]
Trying to type `"{}"` results in `"{(")`. Both`"()"` and `"[]"` work fine.

**Comment by cursiveclojure** [comment]
I can't reproduce this, it works fine for me. Which platform and keyboard layout are you using?

**Comment by immoh** [comment]
Ah, it was the Emacs binding set that bound "Wrap with ()" t Alt+Shift+9 which is } on standard Mac keyboard. Sorry to bother.
