### ISSUE TITLE
datomic stubs no longer available

### ISSUE THREAD

**Issue by rogergl** [cursiveclojure/cursive#708]
The following link is no longer valid: https://cursiveclojure.com/datomic-stubs-0.8.4218.jar

**Comment by awebneck** [comment]
Any progress on this? We could really use this jar in a predictable location.

**Comment by cursiveclojure** [comment]
My apologies for the delay with this - the jar is now updated to the latest datomic version and is at: https://cursiveclojure.com/datomic-stubs-0.9.5153.jar

**Comment by awebneck** [comment]
Sweet, thanks!

**Comment by onetom** [comment]
Just for copy-paste convenience, here is the specific maven command (brought over from the [related thread](https://github.com/cursive-ide/cursive/issues/38#issuecomment-26373091)) which allows you to use `[cursive/datomic-stubs "0.9.5153" :scope "provided"]]` in your `project.clj`:

```
mvn install:install-file -Dfile=$HOME/Downloads/datomic-stubs-0.9.5153.jar -DartifactId=datomic-stubs -Dversion=0.9.5153 -DgroupId=cursive -Dpackaging=jar
```
