### ISSUE TITLE
Searching for tests in Java project is slow with Cursive installed

### ISSUE THREAD

**Issue by cjkent** [cursiveclojure/cursive#710]
I have a Java / Maven project with no Clojure code. When Cursive is installed and I right-click on a folder in the project view and select "run all tests" it takes forever for the tests to start. It feels like several minutes. As soon as I disable Cursive the problem disappears and the tests run almost immediately.

**Comment by cursiveclojure** [comment]
This is very strange, I'm wondering if this is related to #706 since I can't think of anything else that should cause this.

**Comment by cursiveclojure** [comment]
As commented in #706, I haven't been able to reproduce this but I've made a change that I believe should fix it. Please re-open this if you're still seeing the issue after the next release.
