### ISSUE TITLE
:refer-clojure :exclude

### ISSUE THREAD

**Issue by esb-dev** [cursiveclojure/cursive#714]
Since rev 0.1.44 I experience the following behaviour:

Given
```
(ns clj.exclude
  (:refer-clojure :exclude [==])
  (:use clojure.core.logic))
```
Evaluation of
```
(run* [q]
      (== q 1) )
```

runs into an exception:
```
CompilerException java.lang.IllegalStateException: == already refers to: #'clojure.core.logic/== in namespace: ....
```
Hat's wrong?

Kind Regards
Burkhardt  Renz

**Comment by cursiveclojure** [comment]
I'm not sure - I can't think of anything that Cursive would do that would cause that. I don't know anything about how core.logic works, but it's very strange that that error should be produced by `run*` - normally that error happens when referring a var into a namespace.

**Comment by esb-dev** [comment]
Hi,

Can I go back to the previous revision?
I would like to check whether the problem vanishes then. 

Kinds regards,
Burkhardt Renz

**Comment by cursiveclojure** [comment]
Yes, see [Manually Installing Cursive](https://cursiveclojure.com/userguide#downgrading).

**Comment by esb-dev** [comment]
Hi,

I moved back to rev. 0.1.43 and the problem is gone.

What am I doing?

The source is
```
(ns clj.exclude
  (:refer-clojure :exclude [==])
  (:use clojure.core.logic))

(run* [q]
      (== q 1) )
```

I start the REPL, change into the namespace `clj.exclude`and run the two forms.

With 0.1.44 the exception is thrown
```
CompilerException java.lang.IllegalStateException: == already refers to: #'clojure.core.logic/== in namespace:  cli.exclude...
```

In 0.1.43 all is fine.

It seems as if in the evaluation of `(run* ...)` the REPL tries to define `==` from Clojure.core, but
it is already defined by `clojure.core.logic`.

It would be great, if you try to reproduce the situation, so that I can be sure there's no other reason with my project settings.

Kinds regards,
Burkhardt Renz

**Comment by cursiveclojure** [comment]
That is very strange - I'll try to reproduce this.

**Comment by cursiveclojure** [comment]
You were absolutely right, this was a problem introduced in 0.1.44. It's fixed in the next build.
