### ISSUE TITLE
Use map-alignment for let- and for-blocks too

### ISSUE THREAD

**Issue by Menthalion** [cursiveclojure/cursive#716]
Seeing how awesome map alignment is, could you also make an option to use the same alignment in let and for blocks ? I just tried to see what it looks like by wrapping a few let blocks in curly braces and reformatted, and I think it looks great.

It probably would work for cond, condp and other pair-based functions and macros as well.

**Comment by cursiveclojure** [comment]
Yes, this is being tracked all the way back in #129. I'll try to fix this soon.
