### ISSUE TITLE
incorrect arity warnings when calling a protocol-fn that has destructuring binds

### ISSUE THREAD

**Issue by dmarjenburgh** [cursiveclojure/cursive#726]
In the following example:

```clojure
(defprotocol IExample
  (test-1 [_ x])
  (test-2 [_ {x :x}])
  (test-3 [_ [x y]]))

(defn do-example [^IExample example]
  (test-1 example 1)
  (test-2 example {:x 1})
  (test-3 example [1 2]))
```

test-1 will correctly show no arity error.
test-2 and test-3 will give an incorrect arity warning with a red squiggly line.

I came across this when calling a function from a [different library] (https://github.com/clojure-liberator/liberator/blob/master/src/liberator/representation.clj#L16)

**Comment by cursiveclojure** [comment]
I see - this is because of the destructuring in the protocol definition, see [CLJ-1024](http://dev.clojure.org/jira/browse/CLJ-1024) for some discussion. I'll fix this.
