### ISSUE TITLE
Rename keywords is utterly terrifying

### ISSUE THREAD

**Issue by savagematt** [cursiveclojure/cursive#727]
Copy-paste a function:

``` clj
; -> copied from not-initially-scary.clj
(defn some-fn [{:keys [kittens]}]
   (give-key-to-my-house-to kittens))

; -> pasted to not-ever-scary.clj
(defn some-fn [{:keys [kittens]}]
   (give-key-to-my-house-to kittens))
```
In `not-ever-scary.clj`, I shift-F6 on `kittens` and change some other behaviour:

```clj
(defn some-fn [{:keys [monstrous-sociopaths]}]
   (try-to-avoid-electing monstrous-sociopaths))
```

Now in `not-initially-scary.clj` I see:

```clj
(defn some-fn [{:keys [monstrous-sociopaths]}]
   (give-key-to-my-house-to monstrous-sociopaths))
```

I just narrowly escaped a very, very expensive production bug only because some code I just deployed isn't due to run until tomorrow.

Obviously I always sniff my diffs  but the accidental change to `not-initially-scary.clj` was hidden with some other, benign, changes and not immediately obvious.

This is the second time this has hit me. The first time I noticed the problem before I committed.

I guess my suggestion would be that keyword rename should default to local scope and there should be another shortcut for global rename. Or Cursive should ask which one I intended.

**Comment by cursiveclojure** [comment]
Yeah, I've been almost bitten by this myself, and was planning to add a popup asking. I'll do that.

**Comment by cursiveclojure** [comment]
So here's how this works after the fix. When you're renaming a local that destructures a keyword, you'll be asked which you'd like to rename:

![rename-prompt](https://cloud.githubusercontent.com/assets/5589171/6091479/3166b12c-af13-11e4-8f84-609c935c6758.png)

For symmetry, I did the same for find usages, although that's less important:

![find-usages-prompt](https://cloud.githubusercontent.com/assets/5589171/6091482/4d91f398-af13-11e4-8374-3e7086a4d5a9.png)

Whether there's destructuring involved or not, when you rename a keyword there's now a preview panel, which allows you to review all the instances that will be renamed and exclude the ones you don't want to rename:

![rename-preview](https://cloud.githubusercontent.com/assets/5589171/6091489/71f1042c-af13-11e4-9c10-9b7efd47f0ff.png)

This should keep your projects looking like this:

![448](https://cloud.githubusercontent.com/assets/5589171/6091490/7df4cda8-af13-11e4-8997-fa89ccf374ca.jpg)
