### ISSUE TITLE
Issue with Evaluate Expression 

### ISSUE THREAD

**Issue by vincentjames501** [cursiveclojure/cursive#728]
I don't recall if this ever worked for me, but when attempting to evaluate a Clojure expression at a breakpoint in the debugger I always receive the following exception:

```
java.lang.IllegalArgumentException: Not a default method
```

Switching to a Java expression still seems to work nicely.

Is there something that I'm doing wrong of is this a bug?

Below is an image showing what I'm seeing. I'm also using 0.1.45.

http://imgur.com/cxiGFLK

**Comment by cursiveclojure** [comment]
That's strange, I've never seen that. Did that happen with `0.1.44` too? Is there anything in your log?

**Comment by cursiveclojure** [comment]
Sorry, I've just re-read your message where it said you weren't sure if it had ever worked. I'll try to investigate why this might happen.

**Comment by vincentjames501** [comment]
I believe it use to work OK but as I remember the variables names often didn't match 1-1 and I often had to use fully qualified namespaces to call functions. @cursiveclojure , where can I get the log files? Also, this also happened in 0.1.44 and I'm pretty sure that's where it started.

**Comment by cursiveclojure** [comment]
Ok - this functionality was pretty much completely revamped in 0.1.44 to fix the problems you experienced previously. You can get your log files at Help->Show log in Finder/Explorer. Could you mail me the whole thing to cursive@cursiveclojure.com? 

I did some investigating last night, Google doesn't know anything about that exception and I also can't find the exception message in the IntelliJ codebase - I'm not sure where that's coming from.

**Comment by cursiveclojure** [comment]
This is fixed. The issue only manifested itself using an EA version of JDK 8, due to some new validation around the invocation of interface methods. In particular, invocation of interface methods against concrete instances appears to no longer be allowed. I'm not sure whether Clojure programs will have issues with this or not, or if it's just a debugger thing.

Thanks to @vincentjames501 for lots of help diagnosing this!
