### ISSUE TITLE
Editing ClojureScript file freezes editor, memory usage jumps

### ISSUE THREAD

**Issue by jstaffans** [cursiveclojure/cursive#730]
I am working on a [small pet project](https://github.com/jstaffans/pay-me) and just added a [bit of ClojureScript](https://github.com/jstaffans/pay-me/blob/master/src/cljs/pay_me/form.cljs). I am using Cursive 0.1.45.

Whenever I edit the [ClojureScript file](https://github.com/jstaffans/pay-me/blob/master/src/cljs/pay_me/form.cljs), memory usage jumps by ~200 Mb and the editor becomes unresponsive. The editor window also sometimes loses focus when I save the file - I have to click the window to be able to edit the file again.

The slowdown occurs even when `lein cljsbuild auto` is not running.

**Comment by jstaffans** [comment]
I determined that the cause of the slowdown is the declaration of [this function](https://github.com/jstaffans/pay-me/blob/master/src/cljs/pay_me/core.cljs#L13-L19). The slowdown disappears after removing those lines. Any idea what is offensive about those?

**Comment by jstaffans** [comment]
Don't know if it's relevant, but there are some rows like this in the log:

```
2015-02-08 10:46:34,746 [1892038]   INFO - openapi.editor.impl.EditorImpl - Cache hits:16384, total requests:23647,file:///Users/johannes/code/pay-me/src/cljs/pay_me/core.cljs 
``` 

I am using the IdeaVIM plugin.

**Comment by cursiveclojure** [comment]
I can't see anything strange about that, no - thanks for the reproduction case, I'll try to look at this tomorrow.

**Comment by cursiveclojure** [comment]
Which function was it that you identified as the problem? It looks like things have moved around in the repo.

**Comment by jstaffans** [comment]
I thought I had identified a function, but actually the sluggishness seems to be independent of the content of the ClojureScript file. Editing for example [https://github.com/jstaffans/pay-me/blob/master/src/cljs/pay_me/form.cljs](this file) is slow, a keypress taking several seconds to register. Would be interesting to hear if you experience it too.

I have IDEA 14.0.3, build 139.1117.

**Comment by cursiveclojure** [comment]
No, I don't see that. I'm on 14.0.2, but I can't see that making a difference. There have been occasional problems with CLJS and indexing generated code, but that's not consistent with this (it's normally when switching to another app and then back again).

It's a long shot, but could you try disabling IdeaVIM and see if that helps? Also, can you send me a copy of your log? You can mail it to cursive@cursiveclojure.com.

**Comment by jstaffans** [comment]
I tried disabling all my plugins to no effect. I noticed that it is not only the editor that is sluggish, any IDEA command takes several seconds to run when the ClojureScript file is open in the editor window (e.g. Cmd-E for Recent Files). Sent you the log.

**Comment by cursiveclojure** [comment]
This is really strange - I can't think what would be causing this. Does File->Invalidate Caches and Restart help? 

If not, the only thing I can think of would be to create a performance snapshot using the instructions [here](https://intellij-support.jetbrains.com/entries/29983118-Reporting-performance-problems). Unfortunately it's kind of a pain if you're using the community edition.

**Comment by jstaffans** [comment]
"Invalidate caches and restart" did indeed help! Thanks for looking into the issue. I will monitor it for a few days and close this issue if I don't notice any more problems.

**Comment by cursiveclojure** [comment]
Oh great! The IntelliJ indexes can get into a funky state sometimes, and that clears them out and forces a rebuild. Hopefully that should be it.
