### ISSUE TITLE
Structural editing: Able to delete parenthesis at end of file with backspace

### ISSUE THREAD

**Issue by dmarjenburgh** [cursiveclojure/cursive#731]
If the last character of a file is a ), ] or } you can simply delete by putting the caret at the end of the file and pressing backspace.

This behaviour is in 0.1.45

**Comment by cursiveclojure** [comment]
I assume you're using v14? This actually seems to be an IntelliJ bug introduced since v13.1.

**Comment by cursiveclojure** [comment]
See: https://youtrack.jetbrains.com/issue/IDEA-137369 for the gory details.

**Comment by cursiveclojure** [comment]
I've added a workaround for this in the next drop until the root cause is fixed.
