### ISSUE TITLE
New Clojure Namespace with dash names directory incorrectly

### ISSUE THREAD

**Issue by lorddoig** [cursiveclojure/cursive#733]
This had me bamboozled for a while - after a fair many `No such namespace` compilation errors (with ClojureScript, haven't tested plain Clojure) I realised what was going on.

When you right-click in a source directory and hit `New > Clojure Namespace` then enter something like `util.some-thing.something`, the path created (assuming none of these directories exist) is `util/some-thing/something.cljs` when it should be `util/some_thing/something.cljs` (with underscores replacing dashes in directory names.)

It correctly deals with dashes in actual file names, just not directories.

**Comment by dignati** [comment]
I always assumed this was the correct behaviour. If my memory serves me, this works in our project.

**Comment by cursiveclojure** [comment]
No, this is definitely wrong, I just noticed this the other day. I'll fix it soon.
