### ISSUE TITLE
I can't find how debg my code

### ISSUE THREAD

**Issue by cocodrino** [cursiveclojure/cursive#734]
Hi..first thanks for this amazing plugin...now, when I try debug seems not work as expected

1- debug in repl: based in the documentation I set the breakpoints and I try run my project in debug mode, the repl start, then I send to the repl my code (with the breakpoints) but it's evaluated and doesnt respect the breakpoints (maybe I'm doing something wrong or I do't understand how it must works)...

2) following these steps (originally wrote for la clojure plugin)...when I connect my remote debugger fails in the handshake http://blog.tomeklipski.com/2013/04/running-and-debugging-clojure-code-with.html

3) I wish debug a webserver, generally in java/scala I run a remote server and then connect my debugger, is it possible with clojure?...

I'm a bit newbie with clojure so I think than maybe my debugging workflow is not correct, would be great if you can explain me how is the debugging process...thanks!

**Comment by cursiveclojure** [comment]
1. This is strange, this should work. Are you running your configuration using "Debug"? Do you get a debug toolwindow at the bottom of the screen?

2. What's the error you get with the remote debugger?

3. Yes, this should work fine, see https://cursiveclojure.com/archive/842.html

**Comment by cursiveclojure** [comment]
Based on your reply [here](https://github.com/cursiveclojure/cursive/issues/617#issuecomment-74558463) it seems like this is working for you, so I'm going to close this issue.
