### ISSUE TITLE
StartCom Certificates are not trusted by Oracle JVMs by default

### ISSUE THREAD

**Issue by cursiveclojure** [cursiveclojure/cursive#745]
The new exception reporter and statistics sending use HTTPS. Unfortunately the Oracle JDK does not trust the StartCom certificate we use by default, leading to annoying "Untrusted certificate" errors.

**Comment by jenanwise** [comment]
@cursiveclojure Using a fresh Intellij IDEA 14.1.1 install on OSX 10.10.2, I get an untrusted certificate issue for StartCom when I try and add the plugin repository url https://cursiveclojure.com/plugins-14.1.xml

![screen shot 2015-04-08 at 7 57 51 pm](https://cloud.githubusercontent.com/assets/21303/7059672/93c2b3bc-de29-11e4-80f3-9c699d5964c7.png)

**Comment by cursiveclojure** [comment]
Hmm, that's very strange. Previously this error only happened when sending the statistics. If you don't mind doing it you should be able to trust the cert using the button on the popup, and I'll investigate this soon.

**Comment by jenanwise** [comment]
Got it. Thanks!

**Comment by cursiveclojure** [comment]
So I think this issue is because the certs are only registered with IntelliJ when sending the stats, and now more people are using https for the plugin repo. I'll fix this to register them at startup.

**Comment by jenanwise** [comment]
@cursiveclojure It's still an issue when starting from a fresh IntelliJ install, since I'm guessing you get no control over anything before it downloads your code from the untrusted source?

**Comment by cursiveclojure** [comment]
@jenanwise Right, there's not much I can do about that unfortunately, except get my next cert from a registrar that's trusted by the JVM by default. The fix I made will stop the error coming up every time IntelliJ checks for plugin updates, for sending back usage stats, and so on - basically everything after the plugin is installed the first time. It's unfortunate, though.

**Comment by jenanwise** [comment]
@cursiveclojure :thumbsup:
