### ISSUE TITLE
Cannot start a lein REPL in 0.1.46: ClassNotFoundException from PluginClassLoader

### ISSUE THREAD

**Issue by favila** [cursiveclojure/cursive#748]
Running intellij IDEA 14.0.3, JDK 1.8.0_25 on Ubuntu.

After cursive upgrade from 0.1.45 to 0.1.46, I cannot run lein repls from IDEA. I get the following in the event log:

> 11:39:36 AM Compilation completed successfully in 3 sec
> 11:39:39 AM Error running mast-dev-repl: java.lang.ClassNotFoundException: org.springframework.build.aws.maven.PrivateS3Wagon PluginClassLoader[com.cursiveclojure.cursive, 0.1.46], compiling:(NO_SOURCE_PATH:0:0)

I use the lein plugin [s3-wagon-private][1] to provide maven and lein access to private s3-hosted maven repositories. It uses the classname found in the error.

The idea error log doesn't seem to have any useful information:

> 2015-02-17 11:39:32,061 [1367822]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update canceled 
> 2015-02-17 11:39:32,092 [1367853]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update canceled 
> 2015-02-17 11:39:32,174 [1367935]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 63 ms 
> 2015-02-17 11:39:32,174 [1367935]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 1 files to update 
> 2015-02-17 11:39:32,212 [1367973]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update done in 38 ms 
> 2015-02-17 11:39:32,974 [1368735]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update canceled 
> 2015-02-17 11:39:33,043 [1368804]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update canceled 
> 2015-02-17 11:39:33,186 [1368947]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
> 2015-02-17 11:39:33,584 [1369345]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /home/favila/Applications/intellij-14-ce/lib/jps-launcher.jar:/usr/lib/jvm/java-7-oracle/lib/tools.jar:/home/favila/Applications/intellij-14-ce/lib/optimizedFileManager.jar:/home/favila/Applications/intellij-14-ce/lib/ecj-4.4.jar 
> 2015-02-17 11:39:33,623 [1369384]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 565 ms 
> 2015-02-17 11:39:33,623 [1369384]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 3226 files to update 
> 2015-02-17 11:39:36,073 [1371834]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 2875 ms: 0 min 2sec 
> 2015-02-17 11:39:36,755 [1372516]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /home/favila/Applications/intellij-14-ce/lib/jps-launcher.jar:/usr/lib/jvm/java-7-oracle/lib/tools.jar:/home/favila/Applications/intellij-14-ce/lib/optimizedFileManager.jar:/home/favila/Applications/intellij-14-ce/lib/ecj-4.4.jar 
> 2015-02-17 11:39:39,952 [1375713]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update done in 6329 ms 

Note the "use normal process" REPL works fine.

This is basically crippling my ability to work. Is there a way for me to downgrade the cursive plugin back to 0.1.45? I couldn't find instructions with google; closest I got was [this archived mailing list accouncement with link][2], but the archive process seems to have dropped the link to the instructions. I couldn't find generic IDEA plugin instructions either.

[1]: https://github.com/technomancy/s3-wagon-private
[2]: https://cursiveclojure.com/archive/60.html#60

**Comment by favila** [comment]
I downgraded to 0.1.45 successfully. For any future googlers: uninstall the cursive plugin in IDEA, restart, download the plugin via the ["Manually Installing Cursive"][1] instructions, but change the version in the url to the previous version. Then install the plugin in IDEA via the "install from a file" option, restart again, and you're done.

[1]: https://cursiveclojure.com/userguide/

**Comment by cursiveclojure** [comment]
Yes, a couple of people on the mailing list have suffered this error. I'll investigate this now. Sorry about the problems downgrading, that was more explicit in that doc page previously but then that confused people who wanted to manually install the latest version. I'll try to clarify it further.

**Comment by cursiveclojure** [comment]
This seems to be related to [CLJ-979](http://dev.clojure.org/jira/browse/CLJ-979) - something has changed in the way that classes are loaded in Clojure, although I'm still not sure of all the details. The relevant change in Cursive was upgrading from 1.5.1 to 1.7.0-alpha5 internally.

**Comment by cursiveclojure** [comment]
This problem is indeed caused by the fix to CLJ-979. Many thanks to Nicola Mometto for a super quick fix via [CLJ-1663](http://dev.clojure.org/jira/browse/CLJ-1663).
