### ISSUE TITLE
align bindings inside let

### ISSUE THREAD

**Issue by cocodrino** [cursiveclojure/cursive#751]
Hi, it's only a suggestion, would be cool   align the expressions inside a let

```clojure
   (let [url (:url dataMap)
         oauth-parameters (dissoc dataMap :detail)
         param (map-oauth->parameter-string oauth-parameters)
         parameters-string (if encoded? (encode-URI param) (param))]

      (....))


```

to this

```clojure

   (let [url                (:url dataMap)
         oauth-parameters  (dissoc dataMap :detail)
         param              (map-oauth->parameter-string oauth-parameters)
         parameters-string  (if encoded? (encode-URI param) (param))]

      (...))

```

I know than it's not the standart clojure code style but I think than it improves a lot the readability and would be cool almost to have the option inside intellij idea for it...

thanks!!...

**Comment by cursiveclojure** [comment]
Actually, the last version (0.1.46) just added this feature. You can turn it on under Settings->Editor->Code Style->Clojure->General.
