### ISSUE TITLE
Cursive's reader does not allow `clojure.core//` as a symbol: can't eval in REPL

### ISSUE THREAD

**Issue by favila** [cursiveclojure/cursive#755]
Lovely edge case in symbol parsing:

It is not possible to evaluate a form containing `clojure.core//` (the division function) in the REPL because cursive thinks the second `/` is a syntax error (red squiggly underline).

You will also get the syntax error flagged in files, but you can still evaluate the file so it's not as big a deal.

**Comment by cursiveclojure** [comment]
Yeah, this is actually tracked back in #245. I'll try to fix this shortly, although as you say it's not a critical issue.
