### ISSUE TITLE
What each keymap does?

### ISSUE THREAD

**Issue by hansgru** [cursiveclojure/cursive#760]
Is there somewhere listed what each Cursive Keymap does?

I'm using IntelliJ for more than 10 years but for many of the Cursive keymap "actions" I have no idea what is supposed to happen :).

**Comment by cursiveclojure** [comment]
Most of these are documented in the [user guide](https://cursiveclojure.com/userguide/), although it's a little out of date now.

**Comment by hansgru** [comment]
> Most of these are documented in the user guide

Some are "spread" across the user guide, but there's no simple table/overview to know right away what each is intended to do, and how it's different from what the user thinks it should be.
