### ISSUE TITLE
require namespace suggestion pops up in cljs editor when not needed

### ISSUE THREAD

**Issue by henryw-erudine** [cursiveclojure/cursive#763]
this seems to be the same as this issue https://github.com/cursiveclojure/cursive/issues/593, except I see it happening for cljs only.

when agreeing to require the namespace, it appears in the require list of the current ns, even if the entry already exists. as you'd expect for an unrecognised var, you cannot navigate to the required ns from the place where the foreign symbol is used.

**Comment by henryw-erudine** [comment]
I have tried invalidating caches and restarting but to no effect. I am on intellij 13.1, cursive 0.1.48

**Comment by henryw-erudine** [comment]
sorry turned out to be that path to cljs was not in the default lein profile... which i didnt want it to be, but i can work with it.

**Comment by cursiveclojure** [comment]
Ok, so the problem was that the cljs code wasn't under a source root (i.e. a blue folder in the project view)?

**Comment by henryw-erudine** [comment]
yes, i had been tidying an over-large project.clj into various profiles. Ideally in Cursive you could choose which profiles apply to a given project or something, although I'm sure I've read somewhere you have profiles on the todo list anyway, so looking forward to that but for now I'm ok. Thanks
