### ISSUE TITLE
1.48 does not work with latest IJ EAP (IU-140.2683.2)

### ISSUE THREAD

**Issue by gdanov** [cursiveclojure/cursive#769]
The first reason was that in the cursive plugin.xml the until-build was 139.999 so the plugin was disabled as incompatible.
After patching this, I got another, different problem
Caused by: java.lang.ClassNotFoundException: 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException:  [Plugin: com.cursiveclojure.cursive]
...
com.intellij.codeInsight.daemon.impl.PostHighlightingPass PluginClassLoader[com.cursiveclojure.cursive, 0.1.48]

I don't know if it matters, but I am running the EAP version for Mac that uses the bundled jdk 1.8 with fix for font rendering.

**Comment by cursiveclojure** [comment]
Yes, Cursive does not support IDEA 14.1 yet. I hope to fix this soon.

**Comment by cursiveclojure** [comment]
This is tracked in #724.
