### ISSUE TITLE
CLJS REPL executing forms twice

### ISSUE THREAD

**Issue by solicode** [cursiveclojure/cursive#770]
When connected to a CLJS REPL (I'm currently using weasel to do this, but I'm not sure if that's relevant), running `Run top form in REPL` or `Run form before cursor in REPL` is causing the form to be executed twice. I mean that by running a simple statement, this happens:
```clojure
(+ 1 1)
=> 2
=> 2 ; <-- Ran an extra time
```

When running the same command in the mini REPL pane, it correctly executes only one time. I'm thinking it's more likely a bug rather than a setup error since it's behaving inconsistently.

Also, I confirmed that it is indeed running the statement twice and not just printing the result twice.

If you're unable to duplicate it, let me know. I can try coming up with a test project that duplicates this problem.

I'm using Cursive 0.1.48 with IntelliJ 14.0.3.

**Comment by cursiveclojure** [comment]
Ugh, well that was embarrassing - I had a `when` block instead of an `if`. Fixed for the next drop.
