### ISSUE TITLE
SharedLibraryLoaded launch problem for play-cli project in 0.1.48

### ISSUE THREAD

**Issue by Misophistful** [cursiveclojure/cursive#773]
I'm working on a play-cli project, which launched fine in Cursive 0.1.44, but now throws this exception:

```java
GdxRuntimeException Unable to read file for extraction: libgdx64.dylib  com.badlogic.gdx.utils.SharedLibraryLoader.readFile (SharedLibraryLoader.java:126)
```

Could it be related to [#748](https://github.com/cursiveclojure/cursive/issues/748)?

P.S. The same codebase launches perfectly in Light Table (and as mentioned, used to in Cursive), so I'm relatively confident that it's a recent Cursive issue.

**Comment by cursiveclojure** [comment]
I just tried to reproduce this, and I can't. I ran `lein new play-clj cursive-773`, started a REPL in the `desktop` sub-project, and could load both `cursive-773.core.desktop-launcher` and `cursive-773.core` into it. Does that sound like more or less what should trigger it?

**Comment by Misophistful** [comment]
Are you able to evaluate the `-main` function in the `desktop-launcher` namespace, and see the game window appear? (That's the step that triggers the exception for me.)

If the game window does launch for you, then it points back to an error with my environment or project setup. So let me know, and then I can continue to investigate on my end.

**Comment by Misophistful** [comment]
I was able to launch the `-main` function on a new play-cli project, so it looks like it might be something to do with my existing project configuration. I'll keep investigating, and will close this issue if/when I figure out what's going on.

Sorry if I've been leading you on a wild goose chase.

**Comment by Misophistful** [comment]
I've managed to fix the issue. It looks like it was because I had 'Use normal process' selected in my REPL configuration, rather than 'Run with Leiningen'. Now I can launch the game window perfectly.

Sorry that I didn't investigate this further before creating the issue.

**Comment by cursiveclojure** [comment]
Ok, no problem - glad it's working! Thanks for the investigation details too, that's good to know.
