### ISSUE TITLE
CLJS macro resolution needs to be updated for CLJS-948

### ISSUE THREAD

**Issue by sfnelson** [cursiveclojure/cursive#779]
Clojurescript 0.0-2755 and later improve macro resolution support [1][2]. This is extremely useful as it eliminates the need for explicit `:require-macros` when importing a library namespace that defines both clojurescript functions and clojure macros. For example:

```
(ns my-ns
  (:require [my-library.core :as lib]))

;; all of these symbols are resolved from the `lib` require
(lib/a-macro lib/a-symbol lib/a-function)
```

[1] http://dev.clojure.org/jira/browse/CLJS-948
[2] https://github.com/clojure/clojurescript/commit/28e6070691e89f5fe35ae8f8a196ae1048fbf07d

**Comment by cursiveclojure** [comment]
Yes, this is tracked in #775.
