### ISSUE TITLE
REPL empty in 0.1.49 with Idea EAP CE 141.2.2

### ISSUE THREAD

**Issue by paplorinc** [cursiveclojure/cursive#785]
Hello, in Cursive 0.1.49 with latest Idea EAP CE 141.2.2, the REPL won't open for a fresh project with Clojure 1.7 Alpha 1; it's empty after "Initializing", can't find a stack log anywhere though.
Also, to follow the Intellij way, you may want to add the REPL in the Tools menu, next to the *Groovy console*.

It's the first time I'm trying Cursive, I might be doing something wrong, but this is how other REPLs work in Idea :)

**Comment by cursiveclojure** [comment]
Yes, the REPL works a little differently in Cursive - there's some documentation [here](https://cursiveclojure.com/userguide/repl.html). There are a couple of problems with having a single link in the tools menu: firstly Cursive has several different types of REPLs with more coming, and you also want to be able to configure JVM args, environment variables etc. I'm planning to put some instructions in the empty REPL pane so this is clearer. I'll close this now, feel free to re-open if that doesn't work for you.

**Comment by paplorinc** [comment]
As I wrote it in my other comment also, I strongly disagree with documentation-driven application exploration. The user should be able to do it based on previous exposure to similar products, whilst this one should help in non-standard scenarios (e.g. your suggestion). But if the industry has standards for these already (i.e. Idea has other REPLs, and even Eclipse does it differently for Clojure), is the deviation well grounded for sure?

All I'm asking here also, is for the simple behavior to be intuitive, Idea-like, non-reinvented which could lead the user to more complex scenarios (without having to read the external documentation).

Btw, it's funny when I get an email, and the subject says: "Re: cursive" :p

**Comment by paplorinc** [comment]
> firstly Cursive has several different types of REPLs with more coming, and you also want to be able to configure JVM args, environment variables etc

Even in this case, the application could start with the defaults and make it easy to set any of the above, after (possibly with REPL restart).
But having no graceful degradation, because the user might need more memory is not very friendly, in my opinion.

**Comment by cursiveclojure** [comment]
I have at least three REPL configurations I use every day. One is a REPL that I open on the existing IntelliJ instance that I'm working in, one is a remote REPL on an external IntelliJ instance that I'm debugging, and one is a standard process REPL that I use to run my tests. This is very common - someone developing a webapp might have one configuration for the server, one for the client, and one for tests. These configurations are totally different - they are different REPL types, with different classpaths, JVM args and parameters. How do you propose to handle that if not with run configurations?

FWIW I discussed this problem with JetBrains and they recommended the run configuration approach. I believe they're going to use it for the Scala plugin if they don't already, for the same reasons.
