### ISSUE TITLE
Starting local Repl fails with "No matching field found: getConnectionManager ..."

### ISSUE THREAD

**Issue by schmfr** [cursiveclojure/cursive#789]
After updating to Cursive 0.1.49 I get the following error when I start a local repl in IntelliJ.

Error running LocalRepl:
No matching field found: getConnectionManager for class.org.apache.maven.wagon.providers.http.HttpWagon

Starting a repl with "lein repl" works fine. When I remove :certificates from profiles.clj the repl starts even from IntelliJ but this is not a option for me.

I use IntelliJ 14.0.3, Leiningen 2.4.3 and Windows 7 x64. Any suggestions?

**Comment by cursiveclojure** [comment]
The latest Cursive upgraded the bundled lein to 2.5.1. If you use that version on the command line, does that work?

**Comment by schmfr** [comment]
No, with lein 2.5.1. I get the same error on command line.
I didnt know that Cursive brings its own leiningen.
I changed the settings in "Settings, Other Settings, Clojure, Leiningen" to lein 2.4.3. but it seems to have no effect? How can I use lein 2.4.3. with the Cursive 0.1.49?

**Comment by cursiveclojure** [comment]
Unfortunately, you can't. My apologies - this is a confusing piece of configuration. That setting is only used when running Lein tasks and will be removed. I do have a plan to allow multiple versions of leiningen to be used, but that is not implemented yet.

This appears to be a bug in leiningen 2.5.1: technomancy/leiningen#1746. I'll probably have to release a Cursive version with 2.5.0, looks like - ugh.

**Comment by cursiveclojure** [comment]
BTW just to confirm, could you try with 2.5.0, to make sure that it works?

**Comment by schmfr** [comment]
With 2.5.0 it works. We would highly appreciate a Cursive release with lein 2.5.0. Thanks a lot for your support.

**Comment by cursiveclojure** [comment]
I will do this first thing tomorrow. In the meantime, as a workaround you can start a REPL on the command line using `lein repl :headless` with 2.5.0 and then connect to it from Cursive using a remote REPL configuration. See [here](https://cursiveclojure.com/userguide/repl.html) under Remote REPLs.

**Comment by cursiveclojure** [comment]
Could you send me a mail on cursive@cursiveclojure.com? If you're ok with it, I'd like to send you a test build to try before releasing - the lein integration is pretty brittle.
