### ISSUE TITLE
Avoid empty ClojureCodeStyleSettings element in .idea/codeStyleSettings.xml

### ISSUE THREAD

**Issue by orfjackal** [cursiveclojure/cursive#797]
Currently when this plugin is installed, it will add a `ClojureCodeStyleSettings` element to `.idea/codeStyleSettings.xml` even if all Clojure code style settings are at default values and the project doesn't contain any Clojure code.

This is problematic when sharing the code style settings between team members (by having that file commited to version control) when not all team members have the Cursive plugin installed. It results in commit churn because IDEA removes than line when the plugin is not installed, and re-inserts it when the plugin is installed.

The desired behavior would be omit the `ClojureCodeStyleSettings` element when all the Clojure code style settings are at default values.

**Comment by cursiveclojure** [comment]
Yes, this is a problem. Unfortunately this is a general IntelliJ problem and not specific to Cursive - it happens with a lot of plugins. When a plugin has any configuration in the IntelliJ config files, IntelliJ is often quite insistent about adding these elements. I actually have code in there to avoid adding empty elements, I'll try to reproduce this and see if I can do anything.

**Comment by cursiveclojure** [comment]
I've fixed this for the next build - there was a bug in the empty element checking logic.

**Comment by orfjackal** [comment]
Great! :grinning:
