### ISSUE TITLE
Support defrecord "." constructor (ClojureScript)

### ISSUE THREAD

**Issue by milelo** [cursiveclojure/cursive#805]
A defrecord can be constructed with either the "->" form: (->RecordName parameters) or the "." form as deftype: (RecordName. parameters). Cursive doesn't recognise the latter.

**Comment by cursiveclojure** [comment]
I can't reproduce this - can you give me an example of a case which doesn't work correctly?

**Comment by milelo** [comment]
This has already been fixed in the current version of cursive - thanks
