### ISSUE TITLE
Setting to turn off "cannot be resolved" warnings

### ISSUE THREAD

**Issue by jkk** [cursiveclojure/cursive#806]
Due to macro usage, I see lots of unresolved warnings in my project. I understand a solution for the macro issue is in the works, but in the meantime, I would really like to turn the warnings off, so I don't have to see them.

I expected to be able to turn it off under Settings -> Editor -> Inspections -> Clojure, but couldn't find anything there.

**Comment by cursiveclojure** [comment]
This is under `Settings->Other Settings->Clojure->Highlight unresolved symbols`.

**Comment by jkk** [comment]
Oops, thanks - sorry for the noise. And thanks for your work on Cursive, liking it a lot so far.

**Comment by cursiveclojure** [comment]
No problem - I'm glad you're enjoying it!

**Comment by jamieorc** [comment]
Where is this setting now? Not finding it. Cheers!

**Comment by cursive-ide** [comment]
@jamieorc *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;Highlight unresolved symbols*

**Comment by jamieorc** [comment]
Thanks, Colin.
