### ISSUE TITLE
Working around project.clj needing to be in root directory. (For other language support)

### ISSUE THREAD

**Issue by BorisKourt** [cursiveclojure/cursive#819]
*This is not an issue as much as it is a workflow question. Let me provide an example setup:*

I am developing a theme for a web framework. The theme has a ClojureScript component but its *backend* code is built with another language. 

IntelliJ Provides support for that language including auto complete and refactoring, but the theme is a few levels deeper into the framework structure. 

I have the `project.clj` file in the theme folder, as that makes it valid to package and distribute. Unfortunately I can only start a Clojure project with Cursive with the theme directory as root. And that prevents IntelliJ from detecting the rest of the framework *outside* of the theme folder. 

Is there a way, in IntelliJ, to add the surrounding code as a resource without moving the project root away from the theme root (and thus break Cursive requirement)?

When I say surrounding I mean the folder structure ends up being something like:

```clj
backend/admin/
backend/lib/
backend/theme/my-theme/ ;;  <--- Contains the CLJS project opened with Cursive.
backend/theme/some-other-theme
```
Prior to working with the CLJS setup I would just open the folder containing `backend/` and Intellij would detect all the code correctly. 

Can I open a Leiningen project using Cursive with `backend/theme/mytheme/` being the root and then add `backend/` as some addition resource to look at for completion features in the other language?

Sorry if this is a tad confusing and only 40% related to Cursive. Not sure where else is best to ask.

**Comment by cursiveclojure** [comment]
Here's what I think you need to do - create your project in your backup folder, as you did previously. Then create a new module for your CLJS part - you can do this by just importing the `project.clj`, and Cursive should set the module up in the right place. You'll end up with a module for your server side code in the root, and a module for the CLJS part in my-theme. You can make one module depend on the other if you need to access the content of one from the other. Does that work?

**Comment by BorisKourt** [comment]
Yes I believe it will. Ill take a look at setting that up now.

Thank you.

**Comment by cursiveclojure** [comment]
No problem - let me know how it goes.

BTW for general questions like this the Cursive [mailing list](https://cursiveclojure.com/mailinglist.html) is good - there's a lot of people on there using Cursive in weird and wonderful configs, and quite a lot of workflow discussion. Archives are [here](https://cursiveclojure.com/archive/).

**Comment by BorisKourt** [comment]
Ah thanks for that link. Somehow I missed it. Will make sure to keep it in mind!

Going to close this to not clutter your issues feed.
