### ISSUE TITLE
leiningen tasks error with: "error reading cursive.jar..."

### ISSUE THREAD

**Issue by jenanwise** [cursiveclojure/cursive#822]
Running the lein version (or any other) task on a fresh leiningen project results in 43 error lines, all the same, saying:

```
error: error reading /Users/username/Library/Application Support/IdeaIC14/clojure-plugin/lib/cursive.jar; invalid header field name: Build number
```

The task still completes eventually:

```
Leiningen 2.5.0 on Java 1.8.0_20-ea Java HotSpot(TM) 64-Bit Server VM

Process finished with exit code 0
```

Tried with the jdk1.8.0_20.jdk and jdk1.7.0_72.jdk on OSX 10.10.3, IDEA 14.1.1.

**Comment by cursiveclojure** [comment]
I can't reproduce this - how are you running the task? Using the Leiningen toolwindow or creating a new run config? Do you get a stacktrace?

**Comment by bobbywilson0** [comment]
+1 I am also getting this error using `Run > figwheel` which just runs `lein figwheel`.
![screen shot 2015-04-09 at 10 21 24 am](https://cloud.githubusercontent.com/assets/4330/7071397/3ab65746-dea2-11e4-88be-d5e2f2bc4cd5.png)

**Comment by jenanwise** [comment]
@cursiveclojure Using the leiningen tool window, selecting "version" and hitting the play button.

**Comment by cursiveclojure** [comment]
I haven't been able to reproduce this, but I've made a change that I hope will fix it. Please let me know if it's still a problem after the next build.

**Comment by jenanwise** [comment]
@cursiveclojure Confirmed 0.1.53 fixes the issue for me.

**Comment by cursiveclojure** [comment]
@jenanwise Great, thanks for letting me know!
