### ISSUE TITLE
Slurp forwards into quoted vector doesn't work

### ISSUE THREAD

**Issue by spieden** [cursiveclojure/cursive#825]
[] :foo ; slurp forward with cursor inside vector -> [:foo]

'[] :foo ; slurp forward with cursor inside vector and nothing happens

In more complex code I've observed the form after the outermost enclosing form being slurped into same.

**Comment by dmarjenburgh** [comment]
The same happens for lists and maps. Also when with `, ~ and @ prefixes (see #645)

**Comment by cursiveclojure** [comment]
See also #696. I'll close this one.
