### ISSUE TITLE
Debugger: missing "nil" list elements

### ISSUE THREAD

**Issue by fbellomi** [cursiveclojure/cursive#827]
The debugger seems to "skip" nil elements when displaying list contents. 

In the screenshot:

![screen shot 2015-04-11 at 17 39 57](https://cloud.githubusercontent.com/assets/1115842/7110747/bb192dac-e1b6-11e4-8141-661eae646825.png)

element 2 is not displayed and it's nil

**Comment by cursiveclojure** [comment]
This is a config item, see *Settings&rarr;Build...&rarr;Debugger&rarr;Data Views&rarr;Java&rarr;Hide null array elements*

**Comment by fbellomi** [comment]
Thanks, didn't know. 
I close the bug.
