### ISSUE TITLE
Doesn't resolve names when use macros. 

### ISSUE THREAD

**Issue by ddwht** [cursiveclojure/cursive#828]
When I tried Quiescent I found that names of components (when you use defcomponent macros) didn't resolve. The same behavior I found when I used Rum. 

![not-resolved](https://cloud.githubusercontent.com/assets/4960281/7125117/05fa8958-e237-11e4-84df-745961fa2bcd.png)

**Comment by bilus** [comment]
Same here for user-defined macros. If necessary, I'll be happy to provide the source code.

**Comment by cursiveclojure** [comment]
Yes, unfortunately Cursive isn't aware of these yet. I'll close this because there are a couple of issues around this already - see for example #147.
