### ISSUE TITLE
When renaming a namespace, rename it in the Clojure REPL environment

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#832]
Feel free to close this for being ridiculous, I know it's a pretty niche feature.

When I renamed a namespace, I got errors in the namespaces that use it, because when they reload the code they are trying to load a 'new' namespace over the previously aliased namespace. Is it possible to rename the namespace in the REPL environment as well?

**Comment by danielcompton** [comment]
I don't even think this is a great idea anymore.

**Comment by cursiveclojure** [comment]
Hehe, I must admit I hadn't given it much thought yet! I'm actually not even sure it's possible.
