### ISSUE TITLE
Resource folders are being converted to Source folders

### ISSUE THREAD

**Issue by lilinjn** [cursiveclojure/cursive#833]
Hi -- 
my project.clj has the following `:resource-paths ["src/main/resources"]`

Each time I restart cursive or refresh leiningen projects via the Leiningen tab -- the folder gets converted to a "Source" folder -- I have to manually set it back to a resource folder. 

thanks

**Comment by cursiveclojure** [comment]
This is by design, but I can't remember the gory details - I believe it was because resource folders didn't get correctly added to REPL classpaths, but I'm not sure. Is there a reason you need these to be resource folders?

**Comment by lilinjn** [comment]
Yeah there's a reason -- But you might not like the answer :-)

basically my project uses clojure and java  
Many of my java classes have main methods (e.g. various tools and examples and demos) 

I use clojure for all sorts of good things from actual long lived code to incremental development/rapid idea exploration

Outside of intellij I build everything via lein. 

Inside of intellij, I use cursive based projects and love pretty much every moment of that experience!
But when hacking java files with main methods-- I do find it useful to simply right click a file and hit run, which then uses intellij's build system -- I've configure the output dirs so this works fine in terms of incremental compilations etc.  

However, most of my java classes with mains load a resource when run and because the directory is mislabelled the application dies when run through the Intellij build system (it doesn't copy the files).

For now I have a work around (just change the directory back to resource every time i refresh lein or restart intellij) -- I had assumed it was a simple typo but if it's hard to fix no worries.  Great talk at clojure/west by the way (I saw the video).  

Thanks!

**Comment by cursiveclojure** [comment]
Hmm, that's annoying. I'm surprised that it doesn't copy resources from source directories actually, I'm sure I've seen that happen before. Do the files you want copied match the resource patterns under *Settings&rarr;Compiler*? I suspect if you add a pattern that matches them there they will be copied - perhaps from resource folders everything is copied, but from source folders they must match the pattern?

**Comment by lilinjn** [comment]
Yes, of course!  I forgot about that option. that's a much better workaround (all my resources are easily described by an extension).  Feel free to close this issue then....
