### ISSUE TITLE
"No nREPL ack" from debug REPL

### ISSUE THREAD

**Issue by Bill** [cursiveclojure/cursive#842]
Moving to Cursive from CIDER today after @cursiveclojure's inspiring talk at Clojure/West today. REPLs good, breakpoints good, I want both too!

So I created a trivial Leiningen project. The REPL works great (run REPL). Also debugging works great (run app). But when I try to open a **debug REPL**, the debugger starts but I never get to a working REPL. I see the following (I put a few linefeeds in there to see what was going on):

```shell
Starting nREPL server...
/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java
 -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:53037,suspend=y,server=n
 -Dfile.encoding=UTF-8
 -Dclojure.compile.path=/Users/bill/Projects/euler-7/target/base+system+user+dev+repl/classes
 -Deuler-7.version=0.1.0-SNAPSHOT
 -Dclojure.debug=false
 -classpath "/Users/bill/Projects/euler-7/test:/Users/bill/Projects/euler-7/src:/Users/bill/Projects/euler-7/dev-resources:/Users/bill/Projects/euler-7/resources:/Users/bill/Projects/euler-7/target/base+system+user+dev+repl/classes:/Users/bill/.m2/repository/cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-SNAPSHOT.jar:/Users/bill/.m2/repository/org/clojure/tools.trace/0.7.8/tools.trace-0.7.8.jar:/Users/bill/.m2/repository/org/tcrawley/dynapath/0.2.3/dynapath-0.2.3.jar:/Users/bill/.m2/repository/org/clojure/tools.nrepl/0.2.7/tools.nrepl-0.2.7.jar:/Users/bill/.m2/repository/clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar:/Users/bill/.m2/repository/org/clojure/math.numeric-tower/0.0.4/math.numeric-tower-0.0.4.jar:/Users/bill/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/Users/bill/.m2/repository/clj-time/clj-time/0.7.0/clj-time-0.7.0.jar:/Users/bill/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar:/Users/bill/.m2/repository/debugger/debugger/0.1.7/debugger-0.1.7.jar:/Users/bill/.m2/repository/spyscope/spyscope/0.1.5/spyscope-0.1.5.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar"
 clojure.main
 -i /private/var/folders/kl/_00kglyd0hv97sdnvgtbghlr0000gn/T/form-init2825570800705122249.clj

Connected to the target VM, address: '127.0.0.1:53037', transport: 'socket'
No nREPL ack received
Disconnected from the target VM, address: '127.0.0.1:53037', transport: 'socket'
```

Any pointers on what I should try next to troubleshoot this?

My env:
* Cursive 0.1.54
* IDEA 14.1.1
* Clojure 1.6
* JDK 1.7
* OS X Yosemite

**Comment by cursiveclojure** [comment]
That's very strange. If you're at the conference, the best thing to do to troubleshoot it is to come find me :-). Let me know if that's not the case, and I'll think about the best way to figure it out.

**Comment by cursiveclojure** [comment]
So this turned out to be a breakpoint being hit during the main namespace being loaded.

**Comment by Bill** [comment]
Colin pointed out I had a breakpoint set in my -main. That was stopping the REPL from loading.

He pointed out that simply continuing from the breakpoint allowed the REPL to finish starting. Then I had a REPL.

**Comment by souenzzo** [comment]
It's happening here.
Sometimes yes, sometimes no.
In good machines and in bad machines.

**Comment by cursive-ide** [comment]
@souenzzo Try increasing the REPL startup timeout, *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;REPL startup timeout*.

**Comment by simongray** [comment]
> So this turned out to be a breakpoint being hit during the main namespace being loaded.

I spent so much time on debugging this. Thank you for this little snippet.

The worse part was that it somehow worked like 10% of the time, despite the breakpoint being in place.
