### ISSUE TITLE
Cursive fails to parse project.clj

### ISSUE THREAD

**Issue by ohlo** [cursiveclojure/cursive#846]
when a project.clj contains dependencies like this:

```
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [core _]]
```

which has an underscore symbol where typically there would be a string, such as you would have if using lein modules plugin, then there is this exception:

```
clojure.lang.Symbol cannot be cast to java.lang.String
java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.String
	at cursive.leiningen.project.LeiningenProjectsManager.getInterProjectDependencies(LeiningenProjectsManager.java:445)
```

The underscore is used as a placeholder. Even if lein parsed the file and ignored inter project dependencies then that would be better than not being able to use the projects at all. 

Thanks

**Comment by ohlo** [comment]
I'm going to write a plugin to transform my project.clj files to process out the placeholders. i can run that before syncing project with cursive. its not going to be great as i have to re-run every time someone changes any project.clj. 

Shame i cant contribute something to cursive :-)

**Comment by akhudek** [comment]
I've just run into this too, any updates on solutions? Munging flies every time I need to start a repl isn't wonderful.

**Comment by akhudek** [comment]
Ah, temporary work around to starting a repl is to start it on the command line and then use the remote feature to connect.

**Comment by ohlo** [comment]
The repl is only a part of the issue though. If you import/sync the project
from the leiningen projects window in intellij you get errors. This results
in various problems, e.g., libs dont get added to intellij modules etc.

On Mon, Jun 29, 2015 at 11:13 PM, Alexander Hudek <notifications@github.com>
wrote:

> Ah, temporary work around to starting a repl is to start it on the command
> line and then use the remote feature to connect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cursiveclojure/cursive/issues/846#issuecomment-116861953>
> .
>



-- 
@henryw374

**Comment by johnchapin** [comment]
I've been using this workaround to detect if a `project.clj` file is being executed from within IntelliJ/Cursive, and varying the dependency version specification if so:

```clojure
(def running-in-intellij?
  (or
    ;; Leiningen task invocations from Cursive
    (->> (java.lang.management.ManagementFactory/getRuntimeMXBean)
         (.getClassPath ,,,)
         (re-find #"clojure-plugin/lib/leiningen-core" ,,,))
    ;; Module/project import from IntelliJ
    (try
      (Class/forName "cursive.leiningen.project.LeiningenProjectsManager")
      (catch Exception e nil))))

(def dependency-version
  (if running-in-intellij? "0.1.0-SNAPSHOT" :version))

(defproject foo
  :dependencies [[bar/baz ~dependency-version]])
```

While this approach does work, I'd really prefer not to have Cursive-specific workarounds entangled in my build files. @cursiveclojure do you have any other suggestions?

**Comment by akhudek** [comment]
Ok, here is an even better work around. Replace all _ symbols with "_" in project.clj. This will stop the parse errors, but it won't make it pick up the new dependencies. To do that, generate a pom file with lein pom, then open the pom and select to create a new project from it.

**Comment by ohlo** [comment]
I have tried this and not getting far with it... perhaps not doing the
right thing. Do you have modules depending on other modules? That's where
my issue is.

I still had my lein modules, then i created maven projects. Cursive
complained 'module cannot be managed by maven and leiningen at the same
time'. ok, so now then i tried using maven projects only.

now, my run config has to change 'use clojure.main with jvm process' since
the lein projects have gone. it seems the repl is not using the module
checkouts..

any help appreciated. thanks

On Fri, Aug 28, 2015 at 4:54 AM, Alexander Hudek <notifications@github.com>
wrote:

> Ok, here is an even better work around. Replace all _ symbols with "_" in
> project.clj. This will stop the parse errors, but it won't make it pick up
> the new dependencies. To do that, generate a pom file with lein pom, then
> open the pom and select to create a new project from it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cursiveclojure/cursive/issues/846#issuecomment-135625424>
> .
>



-- 
@henryw374

**Comment by ohlo** [comment]
What I am doing currently is using a modified lein-modules plugin (put path to it in .lein-classpath) that rewrites my project files to have dependencies as normal. That works but it is annoying to have to revert/shelve those every time i pull from git.

Ideally it would just generate other project files, with a different name... but if i do that neither lein nor intellij will recognize them.  :-(

**Comment by akhudek** [comment]
Yes, you lose the leiningen integration, but the REPL still works fine with the standard jvm execution. Not as good as a proper fix, but much better than random errors and no symbol/function/namespace lookup.

**Comment by cursiveclojure** [comment]
This is now fully supported as of 0.1.64.
