### ISSUE TITLE
Separate unresolved references into Java interop and other symbols categories

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#850]
When working with code that uses a lot of Java interop there are often a lot of unresolved symbols. The Clojure code inspections identify unresolved references, but combine the Java interop references (which are usually fine), with the Clojure functions being called (which are usually not fine, except when defined through macros).

Would it be possible to split this inspection into two different categories? I realise that identifying the type of usage of an unresolved reference is pretty difficult, but even just splitting between references that start with a `.` and those that don't would make a pretty big difference.

**Comment by cursiveclojure** [comment]
This is fixed in the next build. Cursive now has type inference for Java interop, which means that hopefully, barring bugs in the inference, interop forms marked as warnings will actually be warnings.

**Comment by danielcompton** [comment]
Siiick
