### ISSUE TITLE
Quick Documentation View (^j) for symbol should show symbol's type

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#855]
When I ^J over a symbol (local or otherwise) it would be great if the quick documentation would given some idea as to the type of the symbol, following the same rules as Clojure. This helps a lot at identifying and fixing reflection warnings.

![fan_auth_jwt_-_fan-suite_-____workspaces_fexco_fan-suite_](https://cloud.githubusercontent.com/assets/52660/7376236/4374b710-ed93-11e4-8002-2a228da38ae1.png)

Here if I add type metadata to the build-claim function, then Clojure's compiler should know that it is a org.jose4j.jwt.JwtClaims instance, and that could be part of the quick documentation.

**Comment by cursiveclojure** [comment]
Yes, this would be nice. Cursive actually doesn't propagate type information yet, but I'm planning to add this soon since it'll make interop much nicer.

**Comment by cursiveclojure** [comment]
This will be fixed in the next build. Cursive now has type inference for interop. I'll have to add the type inference from Schema types per your example, but this should be much nicer.

**Comment by cursiveclojure** [comment]
This is added for the next build. There are a couple of omissions which are tricky - type hints from arglists of multi-arity functions are not shown, and some forms have customised types which are correctly inferred but can't be shown in the doc. Types are shown for local variables and from the tag metadata of vars.
