### ISSUE TITLE
sexp selection

### ISSUE THREAD

**Issue by milelo** [cursiveclojure/cursive#861]
I think there should be a way of selecting an sexp with a single key combination but I can't find one.
The best I could find is to place the cursor before "(", press alt-↑ twice; the first time selects "(" the second time selects the sexp.
Maybe this should select the sexp on the first press?

**Comment by cprice404** [comment]
The `Extend Selection` action (mapped to CTRL-W for me but I don't know if that's default) does basically this, I believe?

**Comment by cursiveclojure** [comment]
Extend Selection is what @milelo is using with Alt-up. There's a request for this already with some discussion, #401, so I'll close this one.

**Comment by cursiveclojure** [comment]
See also #741.
