### ISSUE TITLE
Static inner classes not auto-imported correctly

### ISSUE THREAD

**Issue by pkozikow** [cursiveclojure/cursive#862]
Say i have mypackage.MyClass$MyInnerClass. When I start typing it inside a clojure ns, it correctly autocompletes it, but includes a bogus  (mypackage.MyClass MyInnerClass) entry in :import. If I remove this bogus entry and place the cursor where the class is used, it suggest to import it, and after hitting alt-enter it correctly adds (mypackage MyClass$MyInnerClass) to :import.

**Comment by cursiveclojure** [comment]
Yes, this is tracked in #695. I'll fix this for the next build.
