### ISSUE TITLE
can not change keybinding in 14.1.2 maybe vim emulator's problem

### ISSUE THREAD

**Issue by zjhmale** [cursiveclojure/cursive#869]
![2015-05-05 10 39 11](https://cloud.githubusercontent.com/assets/6234553/7466317/0791e67a-f313-11e4-8925-b2560719fdfc.png)

i clicked the fix but nothing happened and the apply button is not highlighted so i can not apply either cursive keybinding or emacs keybinding  so how can i fix this

**Comment by cursiveclojure** [comment]
I'll check why that link isn't opening - what you need to do is go to the Keymaps panel. There you'll have a dropdown with your current keymap in it - you probably have one of the default keymaps selected, which cannot be modified. Click 'Copy' and give your copy a name, then click ok. Now when you go back to the keybindings panel you should be able to apply the keybindings.

**Comment by zjhmale** [comment]
thx!!!  it worked :)
