### ISSUE TITLE
Incorrect arity reported on valid number of parameters

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#870]
I'm getting a mistaken incorrect arity error on [these two function calls](https://github.com/ricardojmendez/tropology/blob/fbfe66734a5e7817465b977fd47c23907ff7024e/src/tropology/api.clj#L57-L58).

![screen shot 2015-05-05 at 12 20 41 pm](https://cloud.githubusercontent.com/assets/31263/7469970/b0b9edd4-f321-11e4-8563-f88ff1b45904.png)

[As you can see on the functions being called](https://github.com/ricardojmendez/tropology/blob/fbfe66734a5e7817465b977fd47c23907ff7024e/src/tropology/db.clj#L262-L277), however, that is the correct arity.

Using IntelliJ EAP IU-141.914 and Cursive 0.1.54

**Comment by kindlychung** [comment]
I had a similar problem: 
![](http://i62.tinypic.com/micrnk.jpg)

The error message is "incorrect arity 2 for preserve-metadata..."

**Comment by kindlychung** [comment]
Here is the code:

  
  (defn preserve-metadata
    [&form expr]
    (let [res (with-meta (gensym "res") (meta &form))]
      `(let [~res ~expr]
         ~res)))
  
  (defmacro OR
    ([] nil)
    ([x] (preserve-metadata &form x))
    ([x & next]
      (preserve-metadata &form `(let [or# ~x] (if or# or# (OR ~@next))))))
  
  ;test
  (def x ^String (OR nil "abc"))
  (meta x)

**Comment by cursiveclojure** [comment]
@kindlychung Your case is a different one - the issue is you're using `&form` as a parameter name. Cursive ignores those parameters when calculating the arity because they're often implicitly passed during macroexpansion. If you rename that parameter to `form` (or anything other than `&form` or `&env`) it should work.

@ricardojmendez I'll try to reproduce your case.

**Comment by cursiveclojure** [comment]
@ricardojmendez I can't reproduce this. Does File->Invalidate caches and Restart help? Do you see this always?

**Comment by ricardojmendez** [comment]
@cursiveclojure The issue went away after invalidating caches. Sorry about that.  Should have thought of it, since I had refactored those functions to remove a parameter a day or so before, but given the issue didn't immediately appear it didn't come to mind.

**Comment by cursiveclojure** [comment]
No worries, glad it's working! All sorts of weird things can happen if the indexes get funky.

**Comment by kindlychung** [comment]
@cursiveclojure  indeed, problem solved. Thanks!
