### ISSUE TITLE
Keyboard shortcuts for "Close bracket-type and newline" using Emacs Keybindings don't work

### ISSUE THREAD

**Issue by markjfisher** [cursiveclojure/cursive#871]
Non of the "Close <type> and newline" keyboard shortcuts work for me in emacs mode.
Choosing the function from the action window works fine.
If I change to the cursive mode shortcuts, they work.

- Pressing alt-shift-0 (close () and newline) inserts a comma
- Pressing alt-shift-] (close {} and newline) inserts the char ’
- Pressing alt-] (close [] and newline) inserts the char ‘

I'm on Mac OS X, IntelliJ 14.1.2 build 141.713

**Comment by cursiveclojure** [comment]
What do you mean when you say "Emacs mode"? Do you have the Emacs keybindings selected? If you go to the keymap panel, you can use the "Find actions by shortcut" button to see what else is assigned to those keys. What do you see there?

**Comment by markjfisher** [comment]
Sorry, yes I meant emacs keybindings chosen from the "Binding Set" dropdown in the Other Settings/Clojure/Keybindings section of Preferences.

If I use the button you suggest, the only action it shows is "Main menu/Edit/Structural Editing/Close () and newline" (and same for other 2 versions {} and [])

**Comment by markjfisher** [comment]
I think this might be this issue https://youtrack.jetbrains.com/issue/IDEA-17392

**Comment by cursiveclojure** [comment]
Yeah, that does look like it - what a pain. Looks like face-smashing is probably the only solution for now, sadly. Apparently that issue is [fixed](https://youtrack.jetbrains.com/issue/IDEA-121638#comment=27-981876) in JDK 8u60, but it's not clear how to use that since it's not GA yet.

**Comment by markjfisher** [comment]
cheers. there are some other solutions in the related bugs I might try out, but I'll close this issue as it's not a cursive issue. great product btw, i'm looking out for when you got paid.
