### ISSUE TITLE
how to customize defmulti code style

### ISSUE THREAD

**Issue by zjhmale** [cursiveclojure/cursive#874]
when i write `defprotocol` the default code style is
![2015-05-07 12 13 52](https://cloud.githubusercontent.com/assets/6234553/7497599/0b6cbcd4-f44e-11e4-9472-71fe71c3eef9.png)

and when i write `defmulti` the default code style is
![2015-05-07 12 13 56](https://cloud.githubusercontent.com/assets/6234553/7497606/1e6e27fa-f44e-11e4-890b-0225e6656b11.png)

and when i open `settings` i can not find where to customize the defmulti code style

![2015-05-07 12 15 59](https://cloud.githubusercontent.com/assets/6234553/7497625/45cc78ec-f44e-11e4-9e56-bc59de703488.png)

there is `defmacro` `defprotocol` and other syntax words but can not find `defmulti` there so how can i fix it

**Comment by cursiveclojure** [comment]
See [this document](https://cursiveclojure.com/userguide/formatting.html).

**Comment by zjhmale** [comment]
cool! thxxxxx!!!! :)
