### ISSUE TITLE
Working directory for project.clj itself

### ISSUE THREAD

**Issue by juskrey** [cursiveclojure/cursive#882]
Currently such constructions in project.clj as
```clojure
:jvm-opts ~(read-string (slurp "jvm-options.edn"))
```
are not possible because working directory while loading project.clj is somewhere in the IDEA internals.

Is it possible to handle that correctly?

Thanks!

**Comment by danielcompton** [comment]
Relates to (dupe of?) #333.

**Comment by cursiveclojure** [comment]
Yeah, I'll close this one since the issue is the same.
