### ISSUE TITLE
External Libraries doesn't match lein

### ISSUE THREAD

**Issue by mfikes** [cursiveclojure/cursive#891]
I created a minimal project for use with ClojureScript that actually doesn't specify the Clojure version, but lets it be determined transitively.

```clojure
(defproject little-schemer "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojurescript "0.0-3269"]
                 [org.omcljs/ambly "0.3.0"]])
```

ClojureScript 0.0-3269 specifies Clojure 1.7.0-beta2
Ambly specifies Clojure 1.6.0

So, the project should end up using 1.7.0-beta2.

This is what `lein deps :tree` shows:

```
$ lein deps :tree
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojurescript "0.0-3269"]
   [com.google.javascript/closure-compiler "v20150505"]
     [args4j "2.0.26"]
     [com.google.code.findbugs/jsr305 "1.3.9"]
     [com.google.code.gson/gson "2.2.4"]
     [com.google.guava/guava "18.0"]
     [com.google.javascript/closure-compiler-externs "v20150505"]
     [com.google.protobuf/protobuf-java "2.5.0"]
   [org.clojure/clojure "1.7.0-beta2"]
   [org.clojure/data.json "0.2.6"]
   [org.clojure/google-closure-library "0.0-20150505-021ed5b3"]
     [org.clojure/google-closure-library-third-party "0.0-20150505-021ed5b3"]
   [org.clojure/tools.reader "0.9.2"]
   [org.mozilla/rhino "1.7R5"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.omcljs/ambly "0.3.0"]
   [com.github.rickyclarkson/jmdns "3.4.2-r353-1"]
```

But, in Cursive, the External Libraries list in the Project navigator indicates `Leiningen: org.clojure/clojure:1.6.0`.

If I remove Ambly as a dependency, and then restart Cursive, then the Clojure dependency in External Libraries switches to 1.7.0-beta2.

**Comment by cursiveclojure** [comment]
#765 reported something similar. I'll check this out and see if I can figure out what's going on.
