### ISSUE TITLE
Slurp forward doesn't work when prefixed with `#?`

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#894]
I'm writing reader conditionals and wanting to wrap existing expressions.

### Steps to reproduce:

1. Type `#?` before an existing form
2. Type `(` and have `)` automatically added by structural editing
3. Use "Slurp forwards" command

### Expected results:

Form is wrapped with ()

### Actual results:

Nothing happens, Slurp forwards doesn't get executed. Using "Wrap with ()" instead of typing `(` and `slurp forwards` works as expected.

**Comment by levand** [comment]
+1, this is definitely an issue for me.

**Comment by danielcompton** [comment]
This behaviour seems to have changed in the a recent version of Cursive, now the behaviour is:

```clj
#?|[:a :b]
```
`|` is the cursor. 

Wrap with ()

```clj
(#?|[):a :b]
```

**Comment by cursiveclojure** [comment]
Hmm, I thought I'd fixed this in the latest build, I'll check this.
