### ISSUE TITLE
Auto syncing `project.clj` when it changed

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#897]
It would be great to have Cursive detect when dependencies change in project.clj, and automatically update to pull them down. You could also display some message in the REPL warning people that their dependencies are out of date when you update the deps.

**Comment by cursiveclojure** [comment]
The problem with auto-syncing is that with Clojure it's pretty difficult to know if the newly-modified project.clj is valid or not. I guess I could try it and see if it fails - it's a little tricky though.

I like the REPL idea, though - in fact, a message in the REPL warning about new dependencies with a link to click to manually update might be the best solution. Or perhaps something similar in the project.clj itself - a banner at the top saying that it's been updated with a link to refresh. So not totally automatic, but more attention-grabbing and easy to do.

**Comment by danielcompton** [comment]
Hmm, a banner would give 90% of the benefits. It's a shame project.clj isn't edn data that can be validated. Or do you mean that the coordinates may be invalid?

**Comment by cursiveclojure** [comment]
No, just that the user might be in the middle of updating it and get distracted and go off for a coffee or whatever, and leave it in an invalid state. It's hard to know when to actually try to update it.

**Comment by erichmond** [comment]
+1 for banner/link

**Comment by danielcompton** [comment]
Handled in #56.
