### ISSUE TITLE
what's the difference between load file in in REPL and sync files in REPL

### ISSUE THREAD

**Issue by zjhmale** [cursiveclojure/cursive#900]
load file just reload current file with modify and sync files will refresh the namespaces and dependencies am i right?

**Comment by cursiveclojure** [comment]
Load file will load the current file and its dependencies if they have been modified. Sync files will load all modified files in dependency order.
BTW for general questions, the Cursive [mailing list](https://cursiveclojure.com/mailinglist.html) is the best place to ask them.

**Comment by zjhmale** [comment]
thx :)
