### ISSUE TITLE
Non-existent working dir setting in REPL config kills IDEA on REPL startup

### ISSUE THREAD

**Issue by favila** [cursiveclojure/cursive#905]
On linux (ubuntu 14.10) using IDEA 14.1.3 and cursive 0.1.54.

Steps to reproduce:

1. Create a local, leinigen REPL configuration.
2. Set working directory to a directory known not to exist.
3. Save and run repl.

Expected:

Working directory error.

Actual:

IDEA becomes frozen and completely unresponsive, and must be killed from the outside.

**Comment by cursiveclojure** [comment]
That is definitely not the expected behaviour.

**Comment by favila** [comment]
I should add: running openjdk-8. (I can try to replicate on other jdks if you need.)

**Comment by pkozikow** [comment]
+1. I was going to file a ticket about this but found this. I'm running MacOS and java 1.7.
