### ISSUE TITLE
REPL configuration working dir should understand Intellij path variables

### ISSUE THREAD

**Issue by favila** [cursiveclojure/cursive#906]
REPL configurations cannot usefully be shared because of the hard-coded working directory: it is unlikely that the absolute path of a project's directory will be the same on every machine.

This could be solved neatly if the working directory field accepted IntelliJ's path variables (e.g. `$PROJECT_DIR$`, `$MODULE_DIR$`, `$USER_DIR$`, or even user-defined ones under "Path Variables" setting) and `$PROJECT_DIR$` should probably be the default for newly-created REPL configs.  Bonus points if other configuration values accept this too. (e.g. environment variables could do path variable expansion?)

**Comment by cursiveclojure** [comment]
I actually thought that IntelliJ automatically substituted those variables, but it's possible I'm not doing something I should be. I'll take a look at this.

**Comment by favila** [comment]
I noticed that exported runConfiguration xml files have path variables in them even though they are never shown in the ui. Also if I try to use a path variable in the UI I run into #905, even though the saved xml looks the same in both cases. I'm not sure what's going on here; perhaps path prefixes are substituted with matching path variables when the xml is saved and path substitution is done when the file is read but what's kept in memory is different?

**Comment by cursiveclojure** [comment]
Right, so how this works is the path variables are expanded when loading the config, and collapsed when saving. This seems like what you need. I'm going to close this, feel free to reopen if it's not what you actually need.
