### ISSUE TITLE
Feature request: Organise Requires

### ISSUE THREAD

**Issue by conan** [cursiveclojure/cursive#912]
I'd like Cursive to be able to automatically alphabetise and nest my requires, for example changing this:
```
(:require [conan.http :as :http]
          [conan.core :refer :all]
          [cheshire.core :as json])
```
to this:
```
(:require [cheshire.core :as json]
          [conan
            [core :refer :all]
            [http :as http])
```

**Comment by cursiveclojure** [comment]
Yeah, there's been an open request for this for a while - see #77. I'll try to get to this soon.

**Comment by conan** [comment]
sorry, couldn't find it through search, my bad
