### ISSUE TITLE
Paredit structural navigation has no means of moving by sexp

### ISSUE THREAD

**Issue by solussd** [cursiveclojure/cursive#918]
There doesn't appear to be an equivalent to `forward-sexp` in Emacs paredit. 

If I had a form like this: 
```
(blah (foo 1 2 3) (bar (+ 9 8 7)))
```
Inside the first set of parens I'd like to be able to navigate so my cursor falls immediately before these sexps in this order:
```
blah, (foo 1 2 3), (bar (+ 9 8 7))
```

**Comment by cursiveclojure** [comment]
Unless I'm misunderstanding, this is what *Navigate&rarr;Structural Movement&rarr;Move Forward/Backward* do. Are they not what you're after?

**Comment by solussd** [comment]
Nope, you're right- I mistook those for single character forward/backward and thought the into/out of sexp ones were the only sexp navigation keymappings, which I have bound to other things. :) Sorry for the noise.
