### ISSUE TITLE
Unable to run tests on REPL because Cursive reverts folder set up

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#919]
I'm getting this on Cursive 0.1.55, didn't really test with previous versions.

I recently moved all tests on tropology [under a single folder](https://github.com/ricardojmendez/tropology/tree/develop/test).  Where before my Clojure tests were under "test/", now they are under "test/clj".  As you can see [here](https://github.com/ricardojmendez/tropology/blob/develop/project.clj), the project has been updated as well.

On the IntelliJ module, the old paths still appear as if "test" was the tests folder, instad of "test/clj".  

![screen shot 2015-06-10 at 12 38 09 pm](https://cloud.githubusercontent.com/assets/31263/8079571/1acd316e-0f6e-11e5-84c0-5f04506e2782.png)

I've tried changing this from both the module UI and modifying the iml directly to set it up as expected.

![screen shot 2015-06-10 at 12 38 23 pm](https://cloud.githubusercontent.com/assets/31263/8079587/3bb0c2e2-0f6e-11e5-99d2-7f08b9646636.png)

While the change seems to initially "stick", it is reverted when I open a REPL,  which leads me to think Cursive is the one changing it as it scans the project. If I close IntelliJ and remove the cache, the folders will have the proper structure I configured for as long as the indices are being rebuilt, and then will revert to the wrong set up above.

This means we can no longer run tests on the Cursive REPL, since it cannot find the relevant files.

```
CompilerException java.io.FileNotFoundException: Could not locate tropology/test/parsing__init.class or tropology/test/parsing.clj on classpath., compiling:(/Users/ricardo/Sources/tropology/test/clj/tropology/test/db_nodes.clj:1:1) 
```

You can download a video of the issue in action here: https://mega.co.nz/#!FpI3DZKa!lmn-gDbg4U1YVievcMtMHbXIRXZ0hY8pp_ErdwGE9Wk

**Comment by cursiveclojure** [comment]
The issue is that the test folders are being set up by the leiningen integration, so they get reset whenever you sync your project. If you add a `:test-paths ["test/clj"]` that should work.

**Comment by ricardojmendez** [comment]
Interesting, I expected leiningen was getting the right paths since I could still run both all tests and specific ones from command line with lein.  Thanks!
