### ISSUE TITLE
Clojurescript core functions are not resolved

### ISSUE THREAD

**Issue by bilus** [cursiveclojure/cursive#931]
This is odd, there are two very similar projects:

https://github.com/bilus/om-reforms

and 

https://github.com/bilus/reagent-reforms

When I open examples/controls/src/controls.cljs in the first one, it highlights everything correctly. This isn't the case with reagent-reforms:

![screen shot 2015-06-22 at 21 21 08](https://cloud.githubusercontent.com/assets/1025537/8290633/a02e1296-1924-11e5-8f49-d32103ebacc4.png)

The projects have identical structure and the "examples/controls/src" folder is marked as Sources Root in both.

Another difference is the application of the import-vars macro in reforms.om (src/reforms/om.cljs) vs reforms.reagent (src/reforms/reagent.cljs). The latter is correctly recognized while in the former project it cannot be resolved:

![screen shot 2015-06-22 at 21 26 55](https://cloud.githubusercontent.com/assets/1025537/8290779/6d1c444e-1925-11e5-8f1a-89f9c97818a8.png)

If you need both .idea folders, please let me know.

As a side note, it doesn't recognize vars pulled into reforms.reagent namespace (reagent.cljs) using import-vars macro but probably you do not expand Clojure macros in Clojurescript code and it uses 'cljs.analyzer.api/ns-interns' in any case.

**Comment by bilus** [comment]
Because the problem is gone after deleting .idea and re-importing the project, here it is:

https://www.dropbox.com/s/5t9fgu9cti97kal/dot_idea.tar?dl=0

I hope it helps.

**Comment by cursiveclojure** [comment]
Thanks, I'll take a look but this is almost certainly the indexes getting a bit funky - in these cases *File&rarr;Invalidate Caches and Restart* usually fixes it.

**Comment by bilus** [comment]
Thanks. If this is the case, it would be useful to have it as a button/menu item in a more intuitive place (next to "Synchronize")? I've tried many things including right-click > "Refresh Leiningen Projects". This was very confusing and this was a fresh new project (I only created it today and it exhibited this problem straight away).

**Comment by cursiveclojure** [comment]
Hmm, it's strange to get it in a new project. I'll take a look at the project and see if I can see anything.

**Comment by bilus** [comment]
When creating reagent-reforms I copied some files over from om-reforms (I remember copying project.clj and individual folders in examples/). I hope it helps.

**Comment by danielcompton** [comment]
I think this might be able to be closed?

**Comment by bilus** [comment]
Yes, thank you. :)
