### ISSUE TITLE
Debug trims last element from sequence

### ISSUE THREAD

**Issue by paplorinc** [cursiveclojure/cursive#934]
Hi,

This might have been already reported (would be strange, if it weren't), but I couldn't find anything similar.

While debugging, I found that the last element from a `seq` isn't displayed at all in Idea, i.e.

    (seq [1 2 3 -2 0])

displays

    0 = {Long@2164} "1"
    1 = {Long@2188} "2"
    2 = {Long@2190} "3"
    3 = {Long@2192} "-2"

while

    (println (seq [1 2 3 -2 0]))

displays all elements correctly.

This seems to appear in the debug window and in the expression evaluation windows (`Alt f8` while debugging)

**Comment by cursiveclojure** [comment]
Interesting - one thing I had noticed is that the reported count of a seq is often, but not always, off by one. I haven't had time to investigate it though. I'll take a look at this at the same time.

**Comment by cursiveclojure** [comment]
This was indeed an off-by-1 error. Amazing that no-one (including me) had noticed it - thanks!
