### ISSUE TITLE
Structural Editing kill issue

### ISSUE THREAD

**Issue by agradl** [cursiveclojure/cursive#937]
Example:
```(or (println proposed-value) (swap! scope-atom (fn [current-value] (assoc current-value attribute-uuid (conj used-values proposed-value))))))))```

killing with cursor just before ```(println proposed-value)``` kills the second arg of ```or``` as well

**Comment by cursiveclojure** [comment]
Yes, that's expected - Kill kills to the last element within your current form, even if the last form extends over multiple lines. If you're expecting only `(println proposed-value)` to be killed, you want Kill Sexp.
