### ISSUE TITLE
Autocomplete implement functions for Reify

### ISSUE THREAD

**Issue by gerritjvv** [cursiveclojure/cursive#939]
In java ide(s) when you extend or implement a class you have an option to generate skeleton methods for the extended class/interface. 
It would be really useful to have this for reify 

e.g (reify Iterator
       "type a shortcut to generate the code below"
        (next [ _ ] )
        (hasNext [ _ ] ))

**Comment by cursiveclojure** [comment]
This actually already works - with the cursor inside the reify form, invoke *Code->Generate* and you'll get the option to either Override or Implement methods. See https://cursiveclojure.com/userguide/editing.html for details.

**Comment by gerritjvv** [comment]
Great!!  Thanks!!
