### ISSUE TITLE
Compilation problem in 0.1.56

### ISSUE THREAD

**Issue by pkozikow** [cursiveclojure/cursive#943]
I'm getting the following error when trying to compile a maven module with clojure code.

Error:Module 'module_name' production: java.lang.ExceptionInInitializerError

I'm pretty sure this didn't happen prior to 0.1.56.

**Comment by cursiveclojure** [comment]
Do you get a stacktrace in the log?

**Comment by cursiveclojure** [comment]
Actually, I can reproduce this - I'll debug it now.

**Comment by cursiveclojure** [comment]
This is something related to the Clojure 1.7.0 upgrade. I can't figure it out now sorry, I'll look at it first thing tomorrow. In the meantime you can install 0.1.55 manually as described [here](https://cursiveclojure.com/userguide/).

**Comment by pkozikow** [comment]
Thank you. I appreciate the effort. I just upgraded our internal repos to Clojure 1.7 and had my share of weird problems.

**Comment by cursiveclojure** [comment]
In this case it was actually my fault - I use a Clojure fork and I must have screwed something up rebasing it onto 1.7. Could you try the build from [here](http://colinfleming.net/piotr/cursive-14.1-0.1.56.zip) and make sure it fixes the problem for you? If so I'll do a full release.

**Comment by pkozikow** [comment]
Seems to be working. Thanks!
