### ISSUE TITLE
Fix spelling on Clojurescript -> ClojureScript

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#950]
When creating a new Clojure namespace:

![screenshot of intellij idea 6-07-15 10 01 02 am](https://cloud.githubusercontent.com/assets/811954/8513587/fd0f6d10-23c5-11e5-992d-a0434ffdb0fa.png)

I think it should be spelled ClojureScript.

**Comment by cursiveclojure** [comment]
Now this is a bug I have time to fix!
