### ISSUE TITLE
Project always loses Clojure 1.7 library dependency

### ISSUE THREAD

**Issue by conan** [cursiveclojure/cursive#959]
I recently upgraded a few (but not all) of my projects from Clojure 1.6 to 1.7.  All of the projects that have been upgraded lose the Clojure 1.7 library dependency every time the project synchronises, so every time I run a REPL or refresh leiningen.  I've recently re-installed Cursive afresh, and am running the latest version of it and Intellij.

I upgraded simply by changing the dependency version in my project.clj.  I've tried re-importing the module.

I can go into the module settings > dependencies tab and add in a new Library dependency for Clojure 1.7 (which has the icon and is listed alongside 1.6) to fix the problem, but it only lasts until Intellij next synchronises the project, which is rarely that long.

**Comment by cursiveclojure** [comment]
That's very strange - I can't reproduce this. Do you get any errors in your log?

**Comment by conan** [comment]
no, no errors.  i've now removed the module and several dependencies of it, invalidated caches and restarted several times, and reimported the project.  seems to be ok now - just needed to keep invalidating for a while!
