### ISSUE TITLE
Editor occasionaly (but permanently) loses keyboard input

### ISSUE THREAD

**Issue by jitlogic** [cursiveclojure/cursive#960]
It seems like some kind of race condition. Sometimes editor completely loses keyboard input and only restart of IntelliJ helps. If there are many projects open (in various windows), all of them have the same symptom. 

It often happens when I often switch between tabs (using alt-arrow keys) and intensively use structural editing features for cut & copy clojure expressions between windows (eg. functions between namespaces etc.) - structural editing manually mapped to some keys, eg. Shift-Ctrl-C, Shift-Ctrl-Y, Shift-Ctrl-K etc.

Might this be related to having idendependent keymaps for java and clojure editors ?

**Comment by cursiveclojure** [comment]
Which platform are you on?

**Comment by jitlogic** [comment]
My platform: Ubuntu 14.04/amd64.

**Comment by cursiveclojure** [comment]
Does this sound like your problem? https://youtrack.jetbrains.com/issue/IDEA-78860

That one appears to be a bug with Java and IBUS. There was some discussion on the Cursive ML recently about this, unfortunately the archives are down right now after a server disk problem. I'll get them up soon and paste a link.

**Comment by jitlogic** [comment]
I'll try described workarounds. Thank you.

**Comment by cursiveclojure** [comment]
Here's the link to the forum archive: https://cursiveclojure.com/archive/1301.html#1306

Since this appears to be a Java issue and not specific to Cursive, I'm going to close this issue. If you see anything to suggest otherwise, please re-open it.
