### ISSUE TITLE
IntelliJ 15 EAP Support?

### ISSUE THREAD

**Issue by aadrian** [cursiveclojure/cursive#964]
Hi,

Are there any plans to support IntelliJ 15 EAP too? The 14.1 version of the plug-in won't run with EAP 15.

I know that there's still quite allot of time until a final 15 release, but many long time IntelliJ users tend to always use the EAPs and give feedback since mostly it's stable enough.

Thanks in advance.

**Comment by cursiveclojure** [comment]
Yes, I'm planning this soon.

**Comment by VladRassokhin** [comment]
@cursiveclojure btw, it's time to change text `Cursive will work with IntelliJ versions 12.1, 13.1, 14 and the 14.1 EAP.` into `Cursive will work with IntelliJ versions 12.1, 13.1, 14 and the 14.1.` on [userguide page](https://cursiveclojure.com/userguide/) :)

**Comment by cursiveclojure** [comment]
Thanks! Yeah, quite a lot of the doc is out of date, and I'm in the process of updating it now.

**Comment by cursiveclojure** [comment]
This is fixed in 0.1.59.
