### ISSUE TITLE
Keyboard shortcut to go to REPL window and set focus on input

### ISSUE THREAD

**Issue by dtanner** [cursiveclojure/cursive#982]
It looks like you've already talked about doing this in this mailing list thread, and it's similar to what I want, so adding the issue here to track it:
https://cursiveclojure.com/archive/1326.html

Currently if I want to go to the REPL and type an arbitrary command, I have to use the mouse to click on the REPL tool window.  It could use a keyboard shortcut.   

It doesn't look like Intellij will let me remap any of the existing Alt-# keymaps, so I don't know of a way to make a keyboard shortcut for opening the REPL any other way.?  Thanks.

**Comment by cursiveclojure** [comment]
You can definitely remap the Alt-# combos, I have the REPL on Alt-9. I've just checked, and for some reason the action appears under *Other* in the Keymap and not under *View->Tool Windows* - I'll look into why. But you can find it by searching for "REPL" - it's the only action which is just called "REPL". Assign that to Alt-9 or whatever, and you should be good to go.

**Comment by dtanner** [comment]
excellent - thanks Colin.
