### ISSUE TITLE
Chiara affecting syntax highlighting

### ISSUE THREAD

**Issue by Ameliorate** [cursiveclojure/cursive#988]
When using chiara functions aren't recognised but code does compile. Currently I'm using mynx however it is somewhat difficult because of the lack of highlighting and autocompletion.

**Comment by danielcompton** [comment]
Two things:
1. Chiara's changes to syntax are pretty radical, e.g. https://github.com/one-more-minute/mynx/blob/master/src/reddit.clj#L9-L18. I doubt Cursive would be able to parse this presently.
2. #147 means that there isn't a good way (yet) for libraries to document that they have macros which introduce new symbols. All of mynx's functions and macros are inside a chiara macro which will defeat any indexing Cursive tries to do.

**Comment by cursiveclojure** [comment]
Right, I wasn't aware of Chiara but the modifications to the syntax are so great that it's extremely unlikely that Cursive will ever support it. I'm going to close this.
