### ISSUE TITLE
Don't suggest if template when typing a namespace alias

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#998]
If I type `<my aliased namespace>/if` then Cursive will pop up a suggestion for the if template. This doesn't really make sense if I've already started typing an alias as I'm wanting something from the aliased namespace.

![screenshot of intellij idea 3-08-15 12 00 30 pm](https://cloud.githubusercontent.com/assets/811954/9028758/49b41e82-39d7-11e5-93e5-7483595cc23d.png)

**Comment by cursiveclojure** [comment]
This is actually already fixed in the next drop as part of the fix for #990.
